import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { FileSignature, Check, Loader2 } from "lucide-react";
import { PaymentCard, type Payment } from "@/components/PaymentCard";

export type Agreement = { id:number; projectId:number; scope:string; deliverables:string; timeline:string; revisions:string; price:string; terms:string; acceptedAt?:string|null; acceptedByUserId?:number|null };

export function AgreementCard({ agreement, canAccept, onChanged }: { agreement:Agreement; canAccept:boolean; onChanged?:(agreement:Agreement,nextStep?:string)=>void }) {
 const [current,setCurrent]=useState(agreement); const [loading,setLoading]=useState(false);
 const accept=async()=>{setLoading(true);try{const r=await fetch(`/api/agreements/${current.id}/accept`,{method:"POST",headers:{"Content-Type":"application/json"}});const data=await r.json();if(!r.ok)throw new Error(data.error||"Unable to accept agreement");setCurrent(data.agreement);onChanged?.(data.agreement,data.nextStep);}catch(e){alert(e instanceof Error?e.message:"Unable to accept agreement");}finally{setLoading(false);}};
 const accepted=!!current.acceptedAt;
 return <div className="space-y-3 w-full max-w-md"><div className="w-full rounded-xl border border-primary/25 bg-card shadow-sm overflow-hidden"><div className="px-4 py-3 border-b border-border bg-primary/5 flex items-center gap-2"><FileSignature size={17} className="text-primary"/><div className="flex-1"><p className="font-semibold text-sm">Project Agreement</p><p className="text-[11px] text-muted-foreground">Formal project terms</p></div><Badge className="text-[10px] bg-primary/10 text-primary border-0">{accepted?"Accepted":"Awaiting Acceptance"}</Badge></div><div className="p-4 space-y-3"><div><p className="text-xs text-muted-foreground">Scope of Work</p><p className="text-sm whitespace-pre-wrap leading-5">{current.scope}</p></div><div><p className="text-xs text-muted-foreground">Deliverables</p><p className="text-sm whitespace-pre-wrap leading-5">{current.deliverables}</p></div><div className="grid grid-cols-2 gap-3"><div><p className="text-xs text-muted-foreground">Timeline</p><p className="text-sm font-medium whitespace-pre-wrap">{current.timeline}</p></div><div><p className="text-xs text-muted-foreground">Revisions</p><p className="text-sm font-medium whitespace-pre-wrap">{current.revisions}</p></div></div><div><p className="text-xs text-muted-foreground">Agreed Price</p><p className="text-lg font-bold text-primary">${current.price}</p></div><div><p className="text-xs text-muted-foreground">Terms</p><p className="text-sm whitespace-pre-wrap leading-5">{current.terms}</p></div>{canAccept&&!accepted&&<Button onClick={accept} disabled={loading} className="w-full gap-2"><Check size={14}/>{loading?<><Loader2 size={14} className="animate-spin"/> Accepting...</>:"Accept Agreement"}</Button>}{accepted&&<div className="rounded-lg bg-primary/10 text-primary text-sm px-3 py-2">Agreement accepted. Payment is now required to start the project.</div>}</div></div>{accepted&&canAccept&&<PaymentCard projectId={current.projectId} amount={current.price} initialPayment={null} onPaid={(payment:Payment)=>onChanged?.(current,"payment_paid")}/>}</div>;
}
