import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { CreditCard, ExternalLink, Loader2, RefreshCw, CheckCircle2 } from "lucide-react";

export type Payment = { id:number; projectId:number; gateway:string; amount:string; currency:string; status:"pending"|"paid"|"failed"|"cancelled"; reference:string; paidAt?:string|null };

export function PaymentCard({ projectId, amount, currency="NGN", initialPayment, onPaid }: { projectId:number; amount:string; currency?:string; initialPayment?:Payment|null; onPaid?:(payment:Payment)=>void }) {
 const [payment,setPayment]=useState<Payment|null>(initialPayment??null); const [loading,setLoading]=useState<"pay"|"verify"|null>(null); const [error,setError]=useState("");
 const initialize=async()=>{setLoading("pay");setError("");try{const r=await fetch(`/api/projects/${projectId}/payments/paystack/initialize`,{method:"POST",headers:{"Content-Type":"application/json"}});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to start payment");if(d.paid&&d.payment){setPayment(d.payment);onPaid?.(d.payment);return;}if(d.reference)setPayment(p=>p?{...p,reference:d.reference}:({id:0,projectId,gateway:"paystack",amount,currency,status:"pending",reference:d.reference}));if(d.authorization_url)window.location.href=d.authorization_url;}catch(e){setError(e instanceof Error?e.message:"Unable to start payment");}finally{setLoading(null);}};
 const verify=async()=>{if(!payment?.reference)return;setLoading("verify");setError("");try{const r=await fetch(`/api/payments/paystack/verify/${encodeURIComponent(payment.reference)}`,{method:"POST",headers:{"Content-Type":"application/json"}});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to verify payment");if(d.paid&&d.payment){setPayment(d.payment);onPaid?.(d.payment);}else setError("Payment has not been confirmed yet. If you just paid, wait a moment and try again.");}catch(e){setError(e instanceof Error?e.message:"Unable to verify payment");}finally{setLoading(null);}};
 const paid=payment?.status==="paid";
 return <div className="w-full max-w-md rounded-xl border border-primary/25 bg-card shadow-sm overflow-hidden"><div className="px-4 py-3 border-b border-border bg-primary/5 flex items-center gap-2"><CreditCard size={17} className="text-primary"/><div className="flex-1"><p className="font-semibold text-sm">Project Payment</p><p className="text-[11px] text-muted-foreground">Secure payment via Paystack</p></div><Badge className="text-[10px] bg-primary/10 text-primary border-0 capitalize">{paid?"Paid":payment?.status??"Payment Pending"}</Badge></div><div className="p-4 space-y-3"><div className="flex items-end justify-between"><div><p className="text-xs text-muted-foreground">Amount due</p><p className="text-2xl font-bold text-primary">{currency} {Number(amount).toLocaleString()}</p></div>{paid&&<CheckCircle2 className="text-primary" size={24}/>}</div>{error&&<div className="rounded-lg bg-destructive/10 text-destructive text-sm px-3 py-2">{error}</div>}{!paid&&<>{!payment?.reference?<Button onClick={initialize} disabled={!!loading} className="w-full gap-2">{loading==="pay"?<><Loader2 size={14} className="animate-spin"/>Starting secure checkout...</>:<>Pay with Paystack <ExternalLink size={14}/></>}</Button>:<Button onClick={verify} disabled={!!loading} className="w-full gap-2">{loading==="verify"?<><Loader2 size={14} className="animate-spin"/>Checking payment...</>:<><RefreshCw size={14}/> Check Payment Status</>}</Button>}</>}{paid&&<div className="rounded-lg bg-primary/10 text-primary text-sm px-3 py-2">Payment confirmed. Your project is now in progress.</div>}</div></div>;
}
