import { useEffect, useState } from "react";
import { useLocation } from "wouter";
import { ClientLayout } from "@/components/ClientLayout";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Check, ChevronLeft, ChevronRight, FileText, Upload } from "lucide-react";
import { useCreateProject, getListProjectsQueryKey } from "@workspace/api-client-react";
import { useQueryClient } from "@tanstack/react-query";

const SERVICE = { name: "Admin Panel", price: 199 };
const moduleOptions = ["Dashboard / Overview", "User Management", "Orders / Transactions", "Products / Services", "Content Management", "Reports / Analytics", "Settings", "Notifications", "Other"];
const roleOptions = ["Admin", "Manager", "Staff", "Support", "Editor", "Custom role", "No special roles"];
const dataOptions = ["Supabase", "Firebase", "Xano", "REST API", "Existing database", "Not decided yet"];
const integrationOptions = ["Authentication", "Payments", "Email", "WhatsApp", "File storage", "Third-party API", "None yet", "Other"];
const STORAGE_KEY = "gbolix-admin-panel-request-draft";
type Draft = { project:string; purpose:string; modules:string[]; roles:string[]; dataBackend:string[]; integrations:string[]; design:string; references:string; fileNames:string[]; notes:string };
const emptyDraft: Draft = { project:"", purpose:"", modules:[], roles:[], dataBackend:[], integrations:[], design:"", references:"", fileNames:[], notes:"" };

export default function AdminPanelRequest(){
  const [,setLocation]=useLocation();
  const queryClient=useQueryClient();
  const createMutation=useCreateProject();
  const [step,setStep]=useState(1);
  const [draft,setDraft]=useState<Draft>(emptyDraft);
  const [submittedCode,setSubmittedCode]=useState<string|null>(null);
  useEffect(()=>{try{const saved=localStorage.getItem(STORAGE_KEY);if(saved)setDraft({...emptyDraft,...JSON.parse(saved)})}catch{}},[]);
  useEffect(()=>{if(draft.project||draft.purpose||draft.design||draft.references||draft.notes||draft.fileNames.length)localStorage.setItem(STORAGE_KEY,JSON.stringify(draft))},[draft]);
  const updateDraft=<K extends keyof Draft>(key:K,value:Draft[K])=>setDraft(c=>({...c,[key]:value}));
  const toggle=(key:"modules"|"roles"|"dataBackend"|"integrations",value:string)=>setDraft(c=>({...c,[key]:c[key].includes(value)?c[key].filter(x=>x!==value):[...c[key],value]}));
  const canContinue=()=>{if(step===1)return draft.project.trim().length>=3;if(step===2)return draft.purpose.trim().length>=10;if(step===3)return draft.modules.length>0;if(step===4)return draft.roles.length>0;if(step===5)return draft.dataBackend.length>0;if(step===6)return draft.integrations.length>0;if(step===7)return Boolean(draft.design);return true};
  const handleFiles=(e:React.ChangeEvent<HTMLInputElement>)=>{const files=Array.from(e.target.files??[]);updateDraft("fileNames",[...new Set([...draft.fileNames,...files.map(f=>f.name)])]);e.target.value=""};
  const handleSubmit=()=>{const requirements={service:SERVICE.name,project_description:draft.project.trim(),admin_panel_purpose:draft.purpose.trim(),modules:draft.modules,user_roles:draft.roles,data_backend:draft.dataBackend,integrations:draft.integrations,design_preference:draft.design,design_references:draft.references.trim(),attached_files:draft.fileNames,additional_notes:draft.notes.trim()};createMutation.mutate({data:{serviceType:SERVICE.name,title:`${SERVICE.name} Request`,description:draft.project.trim(),priority:"medium",price:SERVICE.price,requirements} as any},{onSuccess:p=>{queryClient.invalidateQueries({queryKey:getListProjectsQueryKey()});setSubmittedCode(p.projectCode??`GBX-${p.id}`);localStorage.removeItem(STORAGE_KEY);setStep(9)}})};
  const labels=["Project","Purpose","Modules","Roles","Backend","Integrations","Design","Files"];
  return <ClientLayout><div className="p-4 md:p-6 max-w-3xl mx-auto w-full">
    {step<9&&<div className="mb-7"><div className="flex items-center justify-between mb-3"><div><p className="text-xs font-semibold uppercase tracking-wider text-primary">FlutterFlow / Bubble MVP</p><h1 className="text-2xl font-bold mt-1">Admin Panel Setup</h1></div><span className="text-sm text-muted-foreground">Step {step} of 8</span></div><div className="flex gap-1.5">{labels.map((x,i)=><div key={x} className="flex-1"><div className={`h-1.5 rounded-full ${i+1<=step?"bg-primary":"bg-muted"}`}/><p className="text-[10px] text-muted-foreground mt-1 hidden sm:block">{x}</p></div>)}</div></div>}
    {step===1&&<Question title="What are we building the admin panel for?" description="Tell us what product, app, website, or business the dashboard will manage."><Textarea value={draft.project} onChange={e=>updateDraft("project",e.target.value)} placeholder="Example: A marketplace app where administrators manage users, orders, listings, and reports." rows={7} autoFocus/></Question>}
    {step===2&&<Question title="What should the admin panel help you do?" description="Describe the main purpose and the most important tasks administrators need to perform."><Textarea value={draft.purpose} onChange={e=>updateDraft("purpose",e.target.value)} placeholder="Example: Admins should be able to approve users, manage orders, view revenue, and update platform settings." rows={7} autoFocus/></Question>}
    {step===3&&<Question title="Which modules do you need?" description="Select all sections you want included in the admin panel."><div className="grid gap-2 sm:grid-cols-2">{moduleOptions.map(x=><Choice key={x} selected={draft.modules.includes(x)} onClick={()=>toggle("modules",x)} label={x}/>)}</div></Question>}
    {step===4&&<Question title="Who will use the admin panel?" description="Choose the user roles that should have access. We can define different permissions for each role later."><div className="grid gap-2 sm:grid-cols-2">{roleOptions.map(x=><Choice key={x} selected={draft.roles.includes(x)} onClick={()=>toggle("roles",x)} label={x}/>)}</div></Question>}
    {step===5&&<Question title="What will the admin panel connect to?" description="Select the backend or data source you already use or want us to work with."><div className="grid gap-2 sm:grid-cols-2">{dataOptions.map(x=><Choice key={x} selected={draft.dataBackend.includes(x)} onClick={()=>toggle("dataBackend",x)} label={x}/>)}</div></Question>}
    {step===6&&<Question title="What integrations are required?" description="Select the services the admin panel needs to work with."><div className="grid gap-2 sm:grid-cols-2">{integrationOptions.map(x=><Choice key={x} selected={draft.integrations.includes(x)} onClick={()=>toggle("integrations",x)} label={x}/>)}</div></Question>}
    {step===7&&<Question title="How should the admin panel look?" description="Choose the design direction and optionally share references."><div className="space-y-2">{[["brand","Match my existing brand"],["modern","Modern SaaS dashboard"],["minimal","Clean and minimal"],["existing","Match an existing dashboard"],["help","I need design guidance"]].map(([v,l])=><Choice key={v} selected={draft.design===v} onClick={()=>updateDraft("design",v)} label={l}/>)}</div><div className="mt-5"><label className="text-sm font-medium mb-1.5 block">Design references <span className="text-muted-foreground font-normal">(optional)</span></label><Textarea value={draft.references} onChange={e=>updateDraft("references",e.target.value)} placeholder="Paste dashboard links or describe the style you want." rows={4}/></div></Question>}
    {step===8&&<Question title="Add files or anything else we should know" description="Share screenshots, existing dashboard designs, API documentation, logos, or other helpful material."><label className="border border-dashed border-border rounded-xl p-6 flex flex-col items-center justify-center text-center cursor-pointer hover:border-primary/50"><Upload size={22} className="text-primary mb-2"/><span className="font-medium text-sm">Choose helpful files</span><span className="text-xs text-muted-foreground mt-1">Screenshots, API docs, logos, existing UI, or examples</span><input type="file" multiple className="hidden" onChange={handleFiles}/></label>{draft.fileNames.length>0&&<div className="mt-4 space-y-2">{draft.fileNames.map(n=><div key={n} className="flex items-center gap-2 text-sm bg-muted/40 rounded-lg px-3 py-2"><FileText size={15} className="text-primary"/><span className="truncate">{n}</span></div>)}</div>}<div className="mt-5"><label className="text-sm font-medium mb-1.5 block">Additional notes <span className="text-muted-foreground font-normal">(optional)</span></label><Textarea value={draft.notes} onChange={e=>updateDraft("notes",e.target.value)} placeholder="Anything else our team should know?" rows={5}/></div></Question>}
    {step===9&&!submittedCode&&<section className="bg-card border border-border rounded-xl p-5 md:p-6"><p className="text-xs font-semibold uppercase tracking-wider text-primary">Review & Confirm</p><h1 className="text-2xl font-bold mt-1 mb-6">Review your request</h1><div className="space-y-4"><ReviewRow label="Service" value={`${SERVICE.name} — $${SERVICE.price}`}/><ReviewRow label="Project" value={draft.project}/><ReviewRow label="Purpose" value={draft.purpose}/><ReviewRow label="Modules" value={draft.modules.join(", ")}/><ReviewRow label="User roles" value={draft.roles.join(", ")}/><ReviewRow label="Backend / data" value={draft.dataBackend.join(", ")}/><ReviewRow label="Integrations" value={draft.integrations.join(", ")}/><ReviewRow label="Design" value={designLabel(draft.design)}/>{draft.references&&<ReviewRow label="Design references" value={draft.references}/>} {draft.fileNames.length>0&&<ReviewRow label="Files" value={draft.fileNames.join(", ")}/>} {draft.notes&&<ReviewRow label="Additional notes" value={draft.notes}/>}</div></section>}
    {step===9&&submittedCode&&<section className="text-center py-12"><div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mx-auto mb-6"><Check size={30} className="text-primary"/></div><p className="text-xs font-semibold uppercase tracking-wider text-primary mb-2">Request Submitted</p><h1 className="text-3xl font-bold mb-3">We have received your request.</h1><p className="text-muted-foreground max-w-lg mx-auto mb-7">Our team will review the information and contact you through your project conversation if we need anything else.</p><div className="inline-flex flex-col items-center rounded-xl border border-border bg-card px-8 py-5 mb-7"><span className="text-xs text-muted-foreground uppercase tracking-wider">Project ID</span><span className="text-xl font-bold tracking-wide mt-1">{submittedCode}</span><Badge className="mt-3 bg-primary/10 text-primary border-primary/20">Pending Review</Badge></div><Button onClick={()=>setLocation("/tasks")} className="bg-primary text-primary-foreground hover:bg-primary/90">View My Tasks</Button></section>}
    {step<9&&<div className="flex gap-3 mt-6">{step>1?<Button variant="outline" onClick={()=>setStep(s=>Math.max(s-1,1))} className="flex-1 gap-2"><ChevronLeft size={14}/> Back</Button>:<Button variant="outline" onClick={()=>setLocation("/new-request/flutterflow")} className="flex-1">Back to Services</Button>}<Button onClick={()=>{if(canContinue())setStep(s=>Math.min(s+1,9))}} disabled={!canContinue()} className="flex-1 bg-primary text-primary-foreground hover:bg-primary/90 gap-2">Continue <ChevronRight size={14}/></Button></div>}
    {step===9&&!submittedCode&&<div className="flex gap-3 mt-6"><Button variant="outline" onClick={()=>setStep(8)} className="flex-1">Back</Button><Button onClick={handleSubmit} disabled={createMutation.isPending} className="flex-1 bg-primary text-primary-foreground hover:bg-primary/90">{createMutation.isPending?"Submitting...":"Confirm & Submit"}</Button></div>}
    {createMutation.isError&&<p className="text-sm text-destructive text-center mt-4">We couldn't submit the request. Please try again.</p>}
  </div></ClientLayout>
}
function Question({title,description,children}:{title:string;description:string;children:React.ReactNode}){return <section className="bg-card border border-border rounded-xl p-5 md:p-6"><h2 className="text-2xl font-bold mb-2">{title}</h2><p className="text-sm text-muted-foreground mb-6">{description}</p>{children}</section>}
function Choice({selected,onClick,label}:{selected:boolean;onClick:()=>void;label:string}){return <button type="button" onClick={onClick} className={`w-full flex items-center gap-3 text-left rounded-xl border px-4 py-3.5 transition-all ${selected?"border-primary bg-primary/10":"border-border hover:border-primary/40"}`}><span className={`w-5 h-5 rounded-full border flex items-center justify-center shrink-0 ${selected?"border-primary bg-primary text-primary-foreground":"border-muted-foreground/40"}`}>{selected&&<Check size={12}/>}</span><span className={selected?"font-medium text-primary":"text-sm"}>{label}</span></button>}
function ReviewRow({label,value}:{label:string;value:string}){return <div className="border-b border-border pb-3 last:border-0 last:pb-0"><p className="text-xs text-muted-foreground mb-1">{label}</p><p className="text-sm leading-6 whitespace-pre-wrap">{value}</p></div>}
function designLabel(v:string){const m:Record<string,string>={brand:"Match my existing brand",modern:"Modern SaaS dashboard",minimal:"Clean and minimal",existing:"Match an existing dashboard",help:"I need design guidance"};return m[v]??v}
