import { useEffect, useState } from "react";
import { useLocation } from "wouter";
import { ClientLayout } from "@/components/ClientLayout";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Check, ChevronLeft, ChevronRight } from "lucide-react";
import { useCreateProject, getListProjectsQueryKey } from "@workspace/api-client-react";
import { useQueryClient } from "@tanstack/react-query";

const loginMethods = ["Email + Password", "Google", "Apple", "Phone / OTP", "Facebook", "Other"];
const registrationFields = ["Full name", "Email", "Phone number", "Username", "Profile photo", "Other / custom fields"];
const accountFeatures = ["Login", "Sign up", "Forgot / reset password", "Email verification", "Logout", "Remember me", "Change password", "Account / profile settings"];
const STORAGE_KEY = "gbolix-authentication-request-draft";
type Draft = { projectName:string; platform:string; projectLink:string; appType:string; description:string; methods:string[]; registration:string[]; features:string[]; hasRoles:string; roles:string; design:string; brandColors:string; logo:string; notes:string };
const emptyDraft:Draft={projectName:"",platform:"",projectLink:"",appType:"",description:"",methods:[],registration:[],features:[],hasRoles:"",roles:"",design:"",brandColors:"",logo:"",notes:""};

export default function AuthenticationRequest(){
 const [,setLocation]=useLocation(); const queryClient=useQueryClient(); const createMutation=useCreateProject();
 const [step,setStep]=useState(1); const [draft,setDraft]=useState<Draft>(emptyDraft); const [submittedCode,setSubmittedCode]=useState<string|null>(null);
 useEffect(()=>{try{const saved=localStorage.getItem(STORAGE_KEY);if(saved)setDraft({...emptyDraft,...JSON.parse(saved)});}catch{}},[]);
 useEffect(()=>{if(Object.values(draft).some(v=>Array.isArray(v)?v.length>0:Boolean(v)))localStorage.setItem(STORAGE_KEY,JSON.stringify(draft));},[draft]);
 const update=<K extends keyof Draft>(key:K,value:Draft[K])=>setDraft(c=>({...c,[key]:value}));
 const toggle=(key:"methods"|"registration"|"features",value:string)=>setDraft(c=>({...c,[key]:c[key].includes(value)?c[key].filter(x=>x!==value):[...c[key],value]}));
 const canContinue=()=>{if(step===1)return draft.projectName.trim().length>=2&&Boolean(draft.platform)&&Boolean(draft.appType)&&draft.description.trim().length>=10;if(step===2)return draft.methods.length>0;if(step===3)return draft.registration.length>0;if(step===4)return draft.features.length>0;if(step===5)return Boolean(draft.hasRoles)&&(draft.hasRoles==="no"||draft.roles.trim().length>=5);if(step===6)return Boolean(draft.design);return true;};
 const submit=()=>{const requirements={project_name:draft.projectName.trim(),platform:draft.platform,project_link:draft.projectLink.trim(),app_type:draft.appType,app_description:draft.description.trim(),authentication_methods:draft.methods,registration_fields:draft.registration,account_features:draft.features,has_user_roles:draft.hasRoles,roles_and_permissions:draft.roles.trim(),design_status:draft.design,brand_colors:draft.brandColors.trim(),logo_provided:draft.logo,additional_notes:draft.notes.trim()};createMutation.mutate({data:{serviceType:"Authentication Setup",title:"Authentication Setup Request",description:draft.description.trim(),priority:"medium",price:69,requirements} as any},{onSuccess:p=>{queryClient.invalidateQueries({queryKey:getListProjectsQueryKey()});setSubmittedCode(p.projectCode??`GBX-${p.id}`);localStorage.removeItem(STORAGE_KEY);setStep(9);}})};
 const labels=["Project","Login","Registration","Features","Roles","Design","Requirements","Review"];
 return <ClientLayout><div className="p-4 md:p-6 max-w-3xl mx-auto w-full">
 {step<9&&<div className="mb-7"><div className="flex items-center justify-between mb-3"><div><p className="text-xs font-semibold uppercase tracking-wider text-primary">FlutterFlow / Bubble MVP</p><h1 className="text-2xl font-bold mt-1">Authentication Setup</h1></div><span className="text-sm text-muted-foreground">Step {step} of 8</span></div><div className="flex gap-1.5">{labels.map((x,i)=><div key={x} className="flex-1"><div className={`h-1.5 rounded-full ${i+1<=step?"bg-primary":"bg-muted"}`}/><p className="text-[10px] text-muted-foreground mt-1 hidden sm:block">{x}</p></div>)}</div></div>}
 {step===1&&<Question title="Tell us about your project" description="Give us the basic information we need to set up authentication correctly."><div className="space-y-5"><Field label="Project name"><input className="w-full rounded-md border border-input bg-background px-3 py-2.5 text-sm" value={draft.projectName} onChange={e=>update("projectName",e.target.value)} placeholder="Example: Gbolix Marketplace" autoFocus/></Field><Field label="Platform"><div className="grid grid-cols-2 gap-2"><Choice selected={draft.platform==="FlutterFlow"} onClick={()=>update("platform","FlutterFlow")} label="FlutterFlow"/><Choice selected={draft.platform==="Bubble"} onClick={()=>update("platform","Bubble")} label="Bubble"/></div></Field><Field label="What are you building?"><div className="grid grid-cols-2 gap-2"><Choice selected={draft.appType==="Web app"} onClick={()=>update("appType","Web app")} label="Web app"/><Choice selected={draft.appType==="Mobile app"} onClick={()=>update("appType","Mobile app")} label="Mobile app"/><Choice selected={draft.appType==="Both"} onClick={()=>update("appType","Both")} label="Both"/></div></Field><Field label="Project link (optional)"><input className="w-full rounded-md border border-input bg-background px-3 py-2.5 text-sm" value={draft.projectLink} onChange={e=>update("projectLink",e.target.value)} placeholder="Paste your FlutterFlow/Bubble project or preview link"/></Field><Field label="Briefly describe the app"><Textarea value={draft.description} onChange={e=>update("description",e.target.value)} placeholder="Tell us what the app does and what users should be able to do after signing in." rows={5}/></Field></div></Question>}
 {step===2&&<Question title="Which login methods do you need?" description="Select all authentication methods you want included in the project."><div className="grid gap-2 sm:grid-cols-2">{loginMethods.map(x=><Choice key={x} selected={draft.methods.includes(x)} onClick={()=>toggle("methods",x)} label={x}/>)}</div></Question>}
 {step===3&&<Question title="What information should users provide?" description="Select all fields users should complete when creating an account."><div className="grid gap-2 sm:grid-cols-2">{registrationFields.map(x=><Choice key={x} selected={draft.registration.includes(x)} onClick={()=>toggle("registration",x)} label={x}/>)}</div></Question>}
 {step===4&&<Question title="Which account features should be included?" description="Select all features you need in the authentication system."><div className="grid gap-2 sm:grid-cols-2">{accountFeatures.map(x=><Choice key={x} selected={draft.features.includes(x)} onClick={()=>toggle("features",x)} label={x}/>)}</div></Question>}
 {step===5&&<Question title="Does your app have different user roles?" description="Tell us whether different users need different permissions or areas of the app."><div className="grid gap-2 sm:grid-cols-2"><Choice selected={draft.hasRoles==="no"} onClick={()=>update("hasRoles","no")} label="No, one user type"/><Choice selected={draft.hasRoles==="yes"} onClick={()=>update("hasRoles","yes")} label="Yes, multiple roles"/></div>{draft.hasRoles==="yes"&&<div className="mt-5"><label className="text-sm font-medium mb-1.5 block">List the user roles and what each should access</label><Textarea value={draft.roles} onChange={e=>update("roles",e.target.value)} placeholder="Example: Customer — can place orders. Admin — can manage users and orders." rows={6}/></div>}</Question>}
 {step===6&&<Question title="What do you already have for the design?" description="Tell us how you want the authentication screens to look."><div className="space-y-2"><Choice selected={draft.design==="existing"} onClick={()=>update("design","existing")} label="I have an existing authentication design"/><Choice selected={draft.design==="brand"} onClick={()=>update("design","brand")} label="I have branding but need the screens designed"/><Choice selected={draft.design==="clean"} onClick={()=>update("design","clean")} label="Use a clean professional design"/></div><div className="mt-5 space-y-4"><Field label="Brand colors (optional)"><input className="w-full rounded-md border border-input bg-background px-3 py-2.5 text-sm" value={draft.brandColors} onChange={e=>update("brandColors",e.target.value)} placeholder="Example: #00FF66 and black"/></Field><Field label="Logo (optional)"><div className="flex items-center gap-3"><Choice selected={draft.logo==="yes"} onClick={()=>update("logo","yes")} label="I will provide a logo"/><Choice selected={draft.logo==="no"} onClick={()=>update("logo","no")} label="No logo yet"/></div></Field></div></Question>}
 {step===7&&<Question title="Additional requirements" description="Tell us anything else we should know before we review your request."><Textarea value={draft.notes} onChange={e=>update("notes",e.target.value)} placeholder="Anything specific you want the authentication system to do?" rows={7}/></Question>}
 {step===8&&<Question title="Review your request" description="Review the details below before submitting your Authentication Setup request."><div className="rounded-xl border border-border bg-muted/20 p-4 space-y-3"><Review label="Service" value="Authentication Setup — $69"/><Review label="Project" value={`${draft.projectName} · ${draft.platform} · ${draft.appType}`}/><Review label="Project link" value={draft.projectLink||"Not provided"}/><Review label="Description" value={draft.description}/><Review label="Login methods" value={draft.methods.join(", ")}/><Review label="Registration fields" value={draft.registration.join(", ")}/><Review label="Account features" value={draft.features.join(", ")}/><Review label="User roles" value={draft.hasRoles==="yes"?draft.roles:"One user type"}/><Review label="Design" value={draft.design}/><Review label="Brand colors" value={draft.brandColors||"Not provided"}/><Review label="Logo" value={draft.logo||"Not specified"}/><Review label="Additional requirements" value={draft.notes||"None"}/></div></Question>}
 {step===9&&submittedCode&&<section className="text-center py-12"><div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mx-auto mb-6"><Check size={30} className="text-primary"/></div><p className="text-xs font-semibold uppercase tracking-wider text-primary mb-2">Request Submitted</p><h1 className="text-3xl font-bold mb-3">Authentication request received.</h1><p className="text-muted-foreground max-w-lg mx-auto mb-7">We'll review the requirements and continue through your project conversation if anything else is needed.</p><div className="inline-flex flex-col items-center rounded-xl border border-border bg-card px-8 py-5 mb-7"><span className="text-xs text-muted-foreground uppercase tracking-wider">Project ID</span><span className="text-xl font-bold tracking-wide mt-1">{submittedCode}</span><Badge className="mt-3 bg-primary/10 text-primary border-primary/20">Pending Review</Badge></div><Button onClick={()=>setLocation("/tasks")} className="bg-primary text-primary-foreground hover:bg-primary/90">View My Tasks</Button></section>}
 {step>1&&step<7&&<div className="flex gap-3 mt-6"><Button variant="outline" onClick={()=>setStep(s=>Math.max(1,s-1))} className="flex-1 gap-2"><ChevronLeft size={14}/> Back</Button><Button onClick={()=>canContinue()&&setStep(s=>Math.min(7,s+1))} disabled={!canContinue()} className="flex-1 bg-primary text-primary-foreground hover:bg-primary/90 gap-2">Continue <ChevronRight size={14}/></Button></div>}
 {step===1&&<div className="flex gap-3 mt-6"><Button variant="outline" onClick={()=>setLocation("/new-request/flutterflow")} className="flex-1">Back to MVP Services</Button><Button onClick={()=>canContinue()&&setStep(2)} disabled={!canContinue()} className="flex-1 bg-primary text-primary-foreground hover:bg-primary/90 gap-2">Continue <ChevronRight size={14}/></Button></div>}
 {step===7&&<div className="flex gap-3 mt-6"><Button variant="outline" onClick={()=>setStep(6)} className="flex-1">Back</Button><Button onClick={()=>setStep(8)} className="flex-1 bg-primary text-primary-foreground hover:bg-primary/90 gap-2">Continue <ChevronRight size={14}/></Button></div>}
 {step===8&&<div className="flex gap-3 mt-6"><Button variant="outline" onClick={()=>setStep(7)} className="flex-1">Back</Button><Button onClick={submit} disabled={createMutation.isPending} className="flex-1 bg-primary text-primary-foreground hover:bg-primary/90">{createMutation.isPending?"Submitting...":"Confirm & Submit"}</Button></div>}
 {createMutation.isError&&<p className="text-sm text-destructive text-center mt-4">We couldn't submit the request. Please try again.</p>}
 </div></ClientLayout>
}
function Question({title,description,children}:{title:string;description:string;children:React.ReactNode}){return <section className="bg-card border border-border rounded-xl p-5 md:p-6"><h2 className="text-2xl font-bold mb-2">{title}</h2><p className="text-sm text-muted-foreground mb-6">{description}</p>{children}</section>}
function Choice({selected,onClick,label}:{selected:boolean;onClick:()=>void;label:string}){return <button type="button" onClick={onClick} className={`w-full flex items-center gap-3 text-left rounded-xl border px-4 py-3.5 transition-all ${selected?"border-primary bg-primary/10":"border-border hover:border-primary/40"}`}><span className={`w-5 h-5 rounded-full border flex items-center justify-center shrink-0 ${selected?"border-primary bg-primary text-primary-foreground":"border-muted-foreground/40"}`}>{selected&&<Check size={12}/>}</span><span className={selected?"font-medium text-primary":"text-sm"}>{label}</span></button>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div><label className="text-sm font-medium mb-1.5 block">{label}</label>{children}</div>}
function Review({label,value}:{label:string;value:string}){return <div><p className="text-xs text-muted-foreground">{label}</p><p className="text-sm mt-0.5 whitespace-pre-wrap">{value}</p></div>}
