import { useEffect, useState } from "react";
import { useLocation } from "wouter";
import { ClientLayout } from "@/components/ClientLayout";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Check, ChevronLeft, ChevronRight, FileText, Upload } from "lucide-react";
import { useCreateProject, getListProjectsQueryKey } from "@workspace/api-client-react";
import { useQueryClient } from "@tanstack/react-query";

const SERVICE = { name: "Client Portal", price: 249 };
const portalFeatures=["Client dashboard","Profile / account management","Project or task tracking","Documents / file access","Invoices / payments","Messages / communication","Forms / submissions","Notifications","Reports / activity","Other"];
const clientActions=["View project progress","Submit requests","Upload files","Download files","Send messages","Make payments","View invoices","Update profile","Complete forms","Other"];
const backendOptions=["Supabase","Firebase","Xano","REST API","Existing database","Not decided yet"];
const integrations=["Authentication","Payments","Email","WhatsApp","File storage","Calendar","Third-party API","None yet","Other"];
const STORAGE_KEY="gbolix-client-portal-request-draft";
type Draft={project:string;purpose:string;features:string[];actions:string[];backend:string[];integrations:string[];design:string;references:string;fileNames:string[];notes:string};
const emptyDraft:Draft={project:"",purpose:"",features:[],actions:[],backend:[],integrations:[],design:"",references:"",fileNames:[],notes:""};

export default function ClientPortalRequest(){
 const[,setLocation]=useLocation();const queryClient=useQueryClient();const createMutation=useCreateProject();const[step,setStep]=useState(1);const[draft,setDraft]=useState<Draft>(emptyDraft);const[submittedCode,setSubmittedCode]=useState<string|null>(null);
 useEffect(()=>{try{const s=localStorage.getItem(STORAGE_KEY);if(s)setDraft({...emptyDraft,...JSON.parse(s)})}catch{}},[]);
 useEffect(()=>{if(draft.project||draft.purpose||draft.design||draft.references||draft.notes||draft.fileNames.length)localStorage.setItem(STORAGE_KEY,JSON.stringify(draft))},[draft]);
 const update=<K extends keyof Draft>(k:K,v:Draft[K])=>setDraft(c=>({...c,[k]:v}));
 const toggle=(k:"features"|"actions"|"backend"|"integrations",v:string)=>setDraft(c=>({...c,[k]:c[k].includes(v)?c[k].filter(x=>x!==v):[...c[k],v]}));
 const valid=()=>{if(step===1)return draft.project.trim().length>=3;if(step===2)return draft.purpose.trim().length>=10;if(step===3)return draft.features.length>0;if(step===4)return draft.actions.length>0;if(step===5)return draft.backend.length>0;if(step===6)return draft.integrations.length>0;if(step===7)return Boolean(draft.design);return true};
 const files=(e:React.ChangeEvent<HTMLInputElement>)=>{const fs=Array.from(e.target.files??[]);update("fileNames",[...new Set([...draft.fileNames,...fs.map(f=>f.name)])]);e.target.value=""};
 const submit=()=>{const requirements={service:SERVICE.name,project_description:draft.project.trim(),portal_purpose:draft.purpose.trim(),features:draft.features,client_actions:draft.actions,backend:draft.backend,integrations:draft.integrations,design_preference:draft.design,design_references:draft.references.trim(),attached_files:draft.fileNames,additional_notes:draft.notes.trim()};createMutation.mutate({data:{serviceType:SERVICE.name,title:`${SERVICE.name} Request`,description:draft.project.trim(),priority:"medium",price:SERVICE.price,requirements} as any},{onSuccess:p=>{queryClient.invalidateQueries({queryKey:getListProjectsQueryKey()});setSubmittedCode(p.projectCode??`GBX-${p.id}`);localStorage.removeItem(STORAGE_KEY)}})};
 const labels=["Project","Purpose","Features","Actions","Backend","Integrations","Design","Files"];
 return <ClientLayout><div className="p-4 md:p-6 max-w-3xl mx-auto w-full">
 {step<9&&<div className="mb-7"><div className="flex items-center justify-between mb-3"><div><p className="text-xs font-semibold uppercase tracking-wider text-primary">FlutterFlow / Bubble MVP</p><h1 className="text-2xl font-bold mt-1">Client Portal Setup</h1></div><span className="text-sm text-muted-foreground">Step {step} of 8</span></div><div className="flex gap-1.5">{labels.map((x,i)=><div key={x} className="flex-1"><div className={`h-1.5 rounded-full ${i+1<=step?"bg-primary":"bg-muted"}`}/><p className="text-[10px] text-muted-foreground mt-1 hidden sm:block">{x}</p></div>)}</div></div>}
 {step===1&&<Question title="What are we building the client portal for?" description="Tell us about the business, app, service, or platform the portal will support."><Textarea value={draft.project} onChange={e=>update("project",e.target.value)} placeholder="Example: A service business where clients can track their projects, upload documents, message the team, and view invoices." rows={7} autoFocus/></Question>}
 {step===2&&<Question title="What should clients be able to do?" description="Describe the main purpose of the portal and the experience you want clients to have."><Textarea value={draft.purpose} onChange={e=>update("purpose",e.target.value)} placeholder="Example: Clients should have one place to see project progress, communicate with us, upload files, and manage their account." rows={7} autoFocus/></Question>}
 {step===3&&<Question title="Which portal features do you need?" description="Select all features you want included in the client portal."><div className="grid gap-2 sm:grid-cols-2">{portalFeatures.map(x=><Choice key={x} selected={draft.features.includes(x)} onClick={()=>toggle("features",x)} label={x}/>)}</div></Question>}
 {step===4&&<Question title="What should clients be able to do inside the portal?" description="Select the actions clients need access to after they sign in."><div className="grid gap-2 sm:grid-cols-2">{clientActions.map(x=><Choice key={x} selected={draft.actions.includes(x)} onClick={()=>toggle("actions",x)} label={x}/>)}</div></Question>}
 {step===5&&<Question title="What will the portal connect to?" description="Choose the backend or data source you already have or want us to use."><div className="grid gap-2 sm:grid-cols-2">{backendOptions.map(x=><Choice key={x} selected={draft.backend.includes(x)} onClick={()=>toggle("backend",x)} label={x}/>)}</div></Question>}
 {step===6&&<Question title="What integrations are required?" description="Select the services the portal needs to work with."><div className="grid gap-2 sm:grid-cols-2">{integrations.map(x=><Choice key={x} selected={draft.integrations.includes(x)} onClick={()=>toggle("integrations",x)} label={x}/>)}</div></Question>}
 {step===7&&<Question title="How should the portal look?" description="Choose the design direction and optionally provide references."><div className="space-y-2">{[["brand","Match my existing brand"],["modern","Modern SaaS dashboard"],["minimal","Clean and minimal"],["existing","Match an existing portal/dashboard"],["help","I need design guidance"]].map(([v,l])=><Choice key={v} selected={draft.design===v} onClick={()=>update("design",v)} label={l}/>)}</div><div className="mt-5"><label className="text-sm font-medium mb-1.5 block">Design references <span className="text-muted-foreground font-normal">(optional)</span></label><Textarea value={draft.references} onChange={e=>update("references",e.target.value)} placeholder="Paste links or describe the style you want." rows={4}/></div></Question>}
 {step===8&&<Question title="Add helpful files or notes" description="Share screenshots, existing portal designs, API documentation, logos, or anything else useful."><label className="border border-dashed border-border rounded-xl p-6 flex flex-col items-center justify-center text-center cursor-pointer hover:border-primary/50"><Upload size={22} className="text-primary mb-2"/><span className="font-medium text-sm">Choose helpful files</span><span className="text-xs text-muted-foreground mt-1">Screenshots, API docs, logos, existing UI, or examples</span><input type="file" multiple className="hidden" onChange={files}/></label>{draft.fileNames.length>0&&<div className="mt-4 space-y-2">{draft.fileNames.map(n=><div key={n} className="flex items-center gap-2 text-sm bg-muted/40 rounded-lg px-3 py-2"><FileText size={15} className="text-primary"/><span className="truncate">{n}</span></div>)}</div>}<div className="mt-5"><label className="text-sm font-medium mb-1.5 block">Additional notes <span className="text-muted-foreground font-normal">(optional)</span></label><Textarea value={draft.notes} onChange={e=>update("notes",e.target.value)} placeholder="Anything else our team should know?" rows={5}/></div></Question>}
 {step===9&&!submittedCode&&<section className="bg-card border border-border rounded-xl p-5 md:p-6"><p className="text-xs font-semibold uppercase tracking-wider text-primary">Review & Confirm</p><h1 className="text-2xl font-bold mt-1 mb-6">Review your request</h1><div className="space-y-4"><Row label="Service" value={`${SERVICE.name} — $${SERVICE.price}`}/><Row label="Project" value={draft.project}/><Row label="Purpose" value={draft.purpose}/><Row label="Features" value={draft.features.join(", ")}/><Row label="Client actions" value={draft.actions.join(", ")}/><Row label="Backend" value={draft.backend.join(", ")}/><Row label="Integrations" value={draft.integrations.join(", ")}/><Row label="Design" value={designLabel(draft.design)}/>{draft.references&&<Row label="Design references" value={draft.references}/>} {draft.fileNames.length>0&&<Row label="Files" value={draft.fileNames.join(", ")}/>} {draft.notes&&<Row label="Additional notes" value={draft.notes}/>}</div></section>}
 {step===9&&submittedCode&&<section className="text-center py-12"><div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mx-auto mb-6"><Check size={30} className="text-primary"/></div><p className="text-xs font-semibold uppercase tracking-wider text-primary mb-2">Request Submitted</p><h1 className="text-3xl font-bold mb-3">We have received your request.</h1><p className="text-muted-foreground max-w-lg mx-auto mb-7">Our team will review the information and contact you through your project conversation if we need anything else.</p><div className="inline-flex flex-col items-center rounded-xl border border-border bg-card px-8 py-5 mb-7"><span className="text-xs text-muted-foreground uppercase tracking-wider">Project ID</span><span className="text-xl font-bold tracking-wide mt-1">{submittedCode}</span><Badge className="mt-3 bg-primary/10 text-primary border-primary/20">Pending Review</Badge></div><Button onClick={()=>setLocation("/tasks")} className="bg-primary text-primary-foreground hover:bg-primary/90">View My Tasks</Button></section>}
 {step<9&&<div className="flex gap-3 mt-6">{step>1?<Button variant="outline" onClick={()=>setStep(s=>s-1)} className="flex-1 gap-2"><ChevronLeft size={14}/> Back</Button>:<Button variant="outline" onClick={()=>setLocation("/new-request/flutterflow")} className="flex-1">Back to Services</Button>}<Button onClick={()=>valid()&&setStep(s=>s+1)} disabled={!valid()} className="flex-1 bg-primary text-primary-foreground hover:bg-primary/90 gap-2">Continue <ChevronRight size={14}/></Button></div>}
 {step===9&&!submittedCode&&<div className="flex gap-3 mt-6"><Button variant="outline" onClick={()=>setStep(8)} className="flex-1">Back</Button><Button onClick={submit} disabled={createMutation.isPending} className="flex-1 bg-primary text-primary-foreground hover:bg-primary/90">{createMutation.isPending?"Submitting...":"Confirm & Submit"}</Button></div>}
 {createMutation.isError&&<p className="text-sm text-destructive text-center mt-4">We couldn't submit the request. Please try again.</p>}
 </div></ClientLayout>
}
function Question({title,description,children}:{title:string;description:string;children:React.ReactNode}){return <section className="bg-card border border-border rounded-xl p-5 md:p-6"><h2 className="text-2xl font-bold mb-2">{title}</h2><p className="text-sm text-muted-foreground mb-6">{description}</p>{children}</section>}
function Choice({selected,onClick,label}:{selected:boolean;onClick:()=>void;label:string}){return <button type="button" onClick={onClick} className={`w-full flex items-center gap-3 text-left rounded-xl border px-4 py-3.5 transition-all ${selected?"border-primary bg-primary/10":"border-border hover:border-primary/40"}`}><span className={`w-5 h-5 rounded-full border flex items-center justify-center shrink-0 ${selected?"border-primary bg-primary text-primary-foreground":"border-muted-foreground/40"}`}>{selected&&<Check size={12}/>}</span><span className={selected?"font-medium text-primary":"text-sm"}>{label}</span></button>}
function Row({label,value}:{label:string;value:string}){return <div className="border-b border-border pb-3 last:border-0 last:pb-0"><p className="text-xs text-muted-foreground mb-1">{label}</p><p className="text-sm leading-6 whitespace-pre-wrap">{value}</p></div>}
function designLabel(v:string){const m:Record<string,string>={brand:"Match my existing brand",modern:"Modern SaaS dashboard",minimal:"Clean and minimal",existing:"Match an existing portal/dashboard",help:"I need design guidance"};return m[v]??v}
