import { useState } from "react";
import { useLocation } from "wouter";
import { ClientLayout } from "@/components/ClientLayout";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Check, ChevronLeft, ChevronRight, FileText, Upload } from "lucide-react";
import { useCreateProject, getListProjectsQueryKey } from "@workspace/api-client-react";
import { useQueryClient } from "@tanstack/react-query";

const audiences=["Potential clients / customers","Business partners","Investors","Suppliers / vendors","Employees / recruitment","General corporate audience","Other"];
const purposes=["Introduce the company","Win new clients","Partnership / business development","Investor or funding presentation","Corporate communication","Tender / proposal support","Other"];
const sections=["Company overview","Mission & vision","Core values","Products / services","Key benefits / strengths","Industries / markets served","Company history / milestones","Team / leadership","Clients / partnerships","Projects / achievements","Certifications / awards","Contact information / call to action"];
const styles=["Clean & corporate","Modern & minimal","Premium / executive","Bold & creative","Professional with strong visuals","I have a reference style"];
type Draft={company:string;description:string;industry:string;website:string;audience:string[];purpose:string[];sections:string[];style:string;brand:string;references:string;files:string[];notes:string};
const empty:Draft={company:"",description:"",industry:"",website:"",audience:[],purpose:[],sections:[],style:"",brand:"",references:"",files:[],notes:""};
export default function CompanyProfileRequest(){
 const[,setLocation]=useLocation();const queryClient=useQueryClient();const createMutation=useCreateProject();const[step,setStep]=useState(1);const[draft,setDraft]=useState<Draft>(empty);const[submitted,setSubmitted]=useState<string|null>(null);
 const update=<K extends keyof Draft>(key:K,value:Draft[K])=>setDraft(d=>({...d,[key]:value}));
 const toggle=(key:"audience"|"purpose"|"sections",value:string)=>setDraft(d=>({...d,[key]:d[key].includes(value)?d[key].filter(x=>x!==value):[...d[key],value]}));
 const valid=()=>{if(step===1)return draft.company.trim().length>=2&&draft.description.trim().length>=10;if(step===2)return draft.industry.trim().length>=2;if(step===3)return draft.audience.length>0;if(step===4)return draft.purpose.length>0;if(step===5)return draft.sections.length>0;if(step===6)return !!draft.style;return true};
 const handleFiles=(e:React.ChangeEvent<HTMLInputElement>)=>{const names=Array.from(e.target.files??[]).map(f=>f.name);update("files",[...new Set([...draft.files,...names])]);e.target.value=""};
 const submit=()=>{const requirements={service:"Company Profile",company_name:draft.company.trim(),company_description:draft.description.trim(),industry:draft.industry.trim(),website:draft.website.trim(),target_audience:draft.audience,purpose:draft.purpose,requested_sections:draft.sections,visual_style:draft.style,brand_information:draft.brand.trim(),design_references:draft.references.trim(),attached_files:draft.files,additional_notes:draft.notes.trim()};createMutation.mutate({data:{serviceType:"Company Profile",title:`Company Profile Request — ${draft.company.trim()}`,description:draft.description.trim(),priority:"medium",price:49,requirements} as any},{onSuccess:p=>{queryClient.invalidateQueries({queryKey:getListProjectsQueryKey()});setSubmitted(p.projectCode??`GBX-${p.id}`);}})};
 const labels=["Company","Business","Audience","Purpose","Sections","Style","Files","Review"];
 return <ClientLayout><div className="p-4 md:p-6 max-w-3xl mx-auto w-full"><div className="mb-7"><div className="flex items-center justify-between mb-3"><div><p className="text-xs font-semibold uppercase tracking-wider text-primary">Presentation Design</p><h1 className="text-2xl font-bold mt-1">Company Profile</h1></div><span className="text-sm text-muted-foreground">Step {step} of 8</span></div><div className="flex gap-1.5">{labels.map((x,i)=><div key={x} className="flex-1"><div className={`h-1.5 rounded-full ${i+1<=step?"bg-primary":"bg-muted"}`}/><p className="text-[10px] text-muted-foreground mt-1 hidden sm:block">{x}</p></div>)}</div></div>
 {step===1&&<Question title="Tell us about your company" description="Start with the basic information we'll use to structure the profile."><Field label="Company name" value={draft.company} onChange={v=>update("company",v)} placeholder="Example: Gbolix Digital Operations Studio"/><div className="mt-4"><label className="text-sm font-medium mb-1.5 block">What does your company do?</label><Textarea value={draft.description} onChange={e=>update("description",e.target.value)} placeholder="Describe your company, what you offer, and the main value you provide." rows={6}/></div></Question>}
 {step===2&&<Question title="Business details" description="These details help us make the profile specific to your company."><Field label="Industry / sector" value={draft.industry} onChange={v=>update("industry",v)} placeholder="Example: Technology, construction, consulting"/><div className="mt-4"><Field label="Website" value={draft.website} onChange={v=>update("website",v)} placeholder="https://example.com" optional/></div></Question>}
 {step===3&&<Question title="Who is the profile for?" description="Select everyone who will read or receive the company profile."><div className="grid gap-2 sm:grid-cols-2">{audiences.map(x=><Choice key={x} selected={draft.audience.includes(x)} onClick={()=>toggle("audience",x)} label={x}/>)}</div></Question>}
 {step===4&&<Question title="What is the main purpose?" description="Select everything that applies."><div className="grid gap-2 sm:grid-cols-2">{purposes.map(x=><Choice key={x} selected={draft.purpose.includes(x)} onClick={()=>toggle("purpose",x)} label={x}/>)}</div></Question>}
 {step===5&&<Question title="What should the profile include?" description="Choose the sections you want. You can select as many as needed."><div className="grid gap-2 sm:grid-cols-2">{sections.map(x=><Choice key={x} selected={draft.sections.includes(x)} onClick={()=>toggle("sections",x)} label={x}/>)}</div></Question>}
 {step===6&&<Question title="Choose the visual direction" description="Tell us how you want the company profile to look and feel."><div className="space-y-2">{styles.map(x=><Choice key={x} selected={draft.style===x} onClick={()=>update("style",x)} label={x}/>)}</div><div className="mt-5"><label className="text-sm font-medium mb-1.5 block">Brand information <span className="text-muted-foreground font-normal">(optional)</span></label><Textarea value={draft.brand} onChange={e=>update("brand",e.target.value)} placeholder="Brand colors, fonts, logo guidelines, tone of voice, etc." rows={4}/></div><div className="mt-4"><label className="text-sm font-medium mb-1.5 block">Reference designs <span className="text-muted-foreground font-normal">(optional)</span></label><Textarea value={draft.references} onChange={e=>update("references",e.target.value)} placeholder="Paste links or describe company profiles you like." rows={4}/></div></Question>}
 {step===7&&<Question title="Add company assets and notes" description="Upload materials that will help us create an accurate profile."><label className="border border-dashed border-border rounded-xl p-6 flex flex-col items-center justify-center text-center cursor-pointer hover:border-primary/50"><Upload size={22} className="text-primary mb-2"/><span className="font-medium text-sm">Choose company files</span><span className="text-xs text-muted-foreground mt-1">Logo, company information, images, certificates, previous profiles, or brand files</span><input type="file" multiple className="hidden" onChange={handleFiles}/></label>{draft.files.length>0&&<div className="mt-4 space-y-2">{draft.files.map(n=><div key={n} className="flex items-center gap-2 text-sm bg-muted/40 rounded-lg px-3 py-2"><FileText size={15} className="text-primary"/><span className="truncate">{n}</span></div>)}</div>}<div className="mt-5"><label className="text-sm font-medium mb-1.5 block">Additional notes <span className="text-muted-foreground font-normal">(optional)</span></label><Textarea value={draft.notes} onChange={e=>update("notes",e.target.value)} placeholder="Anything else we should know about your company profile?" rows={5}/></div></Question>}
 {step===8&&!submitted&&<Question title="Review your request" description="Make sure everything is correct before submitting."><div className="space-y-4"><Review label="Service" value="Company Profile — $49"/><Review label="Company" value={draft.company}/><Review label="Description" value={draft.description}/><Review label="Industry" value={draft.industry}/>{draft.website&&<Review label="Website" value={draft.website}/>}<Review label="Audience" value={draft.audience.join(", ")}/><Review label="Purpose" value={draft.purpose.join(", ")}/><Review label="Sections" value={draft.sections.join(", ")}/><Review label="Visual style" value={draft.style}/>{draft.brand&&<Review label="Brand information" value={draft.brand}/>} {draft.references&&<Review label="Reference designs" value={draft.references}/>} {draft.files.length>0&&<Review label="Files" value={draft.files.join(", ")}/>} {draft.notes&&<Review label="Additional notes" value={draft.notes}/>}</div></Question>}
 {step===8&&submitted&&<section className="text-center py-12"><div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mx-auto mb-6"><Check size={30} className="text-primary"/></div><p className="text-xs font-semibold uppercase tracking-wider text-primary mb-2">Request Submitted</p><h1 className="text-3xl font-bold mb-3">Company profile request received</h1><p className="text-muted-foreground max-w-lg mx-auto mb-7">We'll review your requirements and use the project conversation if we need any additional information.</p><div className="inline-flex flex-col items-center rounded-xl border border-border bg-card px-8 py-5 mb-7"><span className="text-xs text-muted-foreground uppercase tracking-wider">Project ID</span><span className="text-xl font-bold tracking-wide mt-1">{submitted}</span><Badge className="mt-3 bg-primary/10 text-primary border-primary/20">Pending Review</Badge></div><Button onClick={()=>setLocation("/tasks")} className="bg-primary text-primary-foreground hover:bg-primary/90">View My Tasks</Button></section>}
 {step<8&&<div className="flex gap-3 mt-6">{step>1?<Button variant="outline" onClick={()=>setStep(s=>s-1)} className="flex-1 gap-2"><ChevronLeft size={14}/> Back</Button>:<Button variant="outline" onClick={()=>setLocation("/new-request/presentation")} className="flex-1">Back to Presentation Services</Button>}<Button onClick={()=>valid()&&setStep(s=>s+1)} disabled={!valid()} className="flex-1 bg-primary text-primary-foreground hover:bg-primary/90 gap-2">Continue <ChevronRight size={14}/></Button></div>}
 {step===8&&!submitted&&<div className="flex gap-3 mt-6"><Button variant="outline" onClick={()=>setStep(7)} className="flex-1">Back</Button><Button onClick={submit} disabled={createMutation.isPending} className="flex-1 bg-primary text-primary-foreground hover:bg-primary/90">{createMutation.isPending?"Submitting...":"Confirm & Submit"}</Button></div>}{createMutation.isError&&<p className="text-sm text-destructive text-center mt-4">We couldn't submit the request. Please try again.</p>}</div></ClientLayout>;
}
function Question({title,description,children}:{title:string;description:string;children:React.ReactNode}){return <section className="bg-card border border-border rounded-xl p-5 md:p-6"><h2 className="text-2xl font-bold mb-2">{title}</h2><p className="text-sm text-muted-foreground mb-6">{description}</p>{children}</section>}
function Field({label,value,onChange,placeholder,optional}:{label:string;value:string;onChange:(v:string)=>void;placeholder:string;optional?:boolean}){return <div><label className="text-sm font-medium mb-1.5 block">{label} {optional&&<span className="text-muted-foreground font-normal">(optional)</span>}</label><input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className="w-full h-11 rounded-md border border-border bg-background px-3 text-sm outline-none focus:border-primary"/></div>}
function Choice({selected,onClick,label}:{selected:boolean;onClick:()=>void;label:string}){return <button type="button" onClick={onClick} className={`w-full flex items-center text-left rounded-xl border px-4 py-3.5 transition-all ${selected?"border-primary bg-primary/10":"border-border hover:border-primary/40"}`}><span className={`w-5 h-5 rounded-full border flex items-center justify-center mr-3 shrink-0 ${selected?"border-primary bg-primary text-primary-foreground":"border-muted-foreground/40"}`}>{selected&&<Check size={12}/>}</span><span className={selected?"font-medium text-primary":"text-sm"}>{label}</span></button>}
function Review({label,value}:{label:string;value:string}){return <div className="border-b border-border pb-3 last:border-0 last:pb-0"><p className="text-xs text-muted-foreground mb-1">{label}</p><p className="text-sm leading-6 whitespace-pre-wrap">{value}</p></div>}
