import { useState } from "react";
import { useLocation } from "wouter";
import { ClientLayout } from "@/components/ClientLayout";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Check, ChevronLeft, ChevronRight, FileText, Upload } from "lucide-react";
import { useCreateProject, getListProjectsQueryKey } from "@workspace/api-client-react";
import { useQueryClient } from "@tanstack/react-query";

const reasons=["Make it look more modern","Improve visual consistency","Make it more professional","Improve readability / structure","Prepare it for a client or investor","Refresh an outdated design","Other"];
const audiences=["Clients / customers","Investors","Business partners","Internal team","General audience","Other"];
const keep=["Existing wording / content","Existing brand colors","Existing logo / branding","Existing charts / data","Existing slide structure","I'm open to content/layout changes"];
const styles=["Clean & corporate","Modern & minimal","Premium / executive","Bold & creative","Technology / startup","Match a reference design"];
const output=["Keep the same number of slides","Reduce the number of slides if possible","Add slides where needed","I'm open to restructuring"];
type Draft={project:string;reasons:string[];audience:string[];keep:string[];style:string;output:string[];brand:string;references:string;files:string[];notes:string};
const empty:Draft={project:"",reasons:[],audience:[],keep:[],style:"",output:[],brand:"",references:"",files:[],notes:""};
export default function ExistingDeckRedesignRequest(){
 const[,setLocation]=useLocation();const queryClient=useQueryClient();const createMutation=useCreateProject();const[step,setStep]=useState(1);const[draft,setDraft]=useState<Draft>(empty);const[submitted,setSubmitted]=useState<string|null>(null);
 const update=<K extends keyof Draft>(key:K,value:Draft[K])=>setDraft(d=>({...d,[key]:value}));
 const toggle=(key:"reasons"|"audience"|"keep"|"output",value:string)=>setDraft(d=>({...d,[key]:d[key].includes(value)?d[key].filter(x=>x!==value):[...d[key],value]}));
 const valid=()=>{if(step===1)return draft.project.trim().length>=10;if(step===2)return draft.reasons.length>0;if(step===3)return draft.audience.length>0;if(step===4)return draft.keep.length>0;if(step===5)return draft.style.length>0;if(step===6)return draft.output.length>0;return true};
 const handleFiles=(e:React.ChangeEvent<HTMLInputElement>)=>{const names=Array.from(e.target.files??[]).map(f=>f.name);update("files",[...new Set([...draft.files,...names])]);e.target.value=""};
 const submit=()=>{const requirements={service:"Existing Deck Redesign",price:39,existing_deck_description:draft.project.trim(),redesign_goals:draft.reasons,target_audience:draft.audience,content_to_preserve:draft.keep,visual_style:draft.style,slide_output_preference:draft.output,brand_information:draft.brand.trim(),design_references:draft.references.trim(),attached_files:draft.files,additional_notes:draft.notes.trim()};createMutation.mutate({data:{serviceType:"Existing Deck Redesign",title:"Existing Deck Redesign Request",description:draft.project.trim(),priority:"medium",price:39,requirements} as any},{onSuccess:p=>{queryClient.invalidateQueries({queryKey:getListProjectsQueryKey()});setSubmitted(p.projectCode??`GBX-${p.id}`);}})};
 const labels=["Deck","Goals","Audience","Keep","Style","Output","Files","Review"];
 return <ClientLayout><div className="p-4 md:p-6 max-w-3xl mx-auto w-full"><div className="mb-7"><div className="flex items-center justify-between mb-3"><div><p className="text-xs font-semibold uppercase tracking-wider text-primary">Presentation Design</p><h1 className="text-2xl font-bold mt-1">Existing Deck Redesign</h1></div><span className="text-sm text-muted-foreground">Step {step} of 8</span></div><div className="flex gap-1.5">{labels.map((x,i)=><div key={x} className="flex-1"><div className={`h-1.5 rounded-full ${i+1<=step?"bg-primary":"bg-muted"}`}/><p className="text-[10px] text-muted-foreground mt-1 hidden sm:block">{x}</p></div>)}</div></div>
 {step===1&&<Question title="Tell us about the existing deck" description="Describe what you already have and what you want improved."><Textarea value={draft.project} onChange={e=>update("project",e.target.value)} placeholder="Example: I have a 12-slide company presentation that needs a more modern, professional design while keeping the core information." rows={8} autoFocus/></Question>}
 {step===2&&<Question title="What should the redesign improve?" description="Select everything that applies."><div className="grid gap-2 sm:grid-cols-2">{reasons.map(x=><Choice key={x} selected={draft.reasons.includes(x)} onClick={()=>toggle("reasons",x)} label={x}/>)}</div></Question>}
 {step===3&&<Question title="Who is the deck for?" description="Select the main audience for the redesigned presentation."><div className="grid gap-2 sm:grid-cols-2">{audiences.map(x=><Choice key={x} selected={draft.audience.includes(x)} onClick={()=>toggle("audience",x)} label={x}/>)}</div></Question>}
 {step===4&&<Question title="What should we preserve?" description="Tell us what must remain from your current deck. Select all that apply."><div className="grid gap-2 sm:grid-cols-2">{keep.map(x=><Choice key={x} selected={draft.keep.includes(x)} onClick={()=>toggle("keep",x)} label={x}/>)}</div></Question>}
 {step===5&&<Question title="Choose the new visual direction" description="Select the style you want for the redesign."><div className="space-y-2">{styles.map(x=><Choice key={x} selected={draft.style===x} onClick={()=>update("style",x)} label={x}/>)}</div><div className="mt-5"><label className="text-sm font-medium mb-1.5 block">Brand information <span className="text-muted-foreground font-normal">(optional)</span></label><Textarea value={draft.brand} onChange={e=>update("brand",e.target.value)} placeholder="Brand colors, fonts, logo rules, or other guidelines." rows={4}/></div><div className="mt-4"><label className="text-sm font-medium mb-1.5 block">Reference designs <span className="text-muted-foreground font-normal">(optional)</span></label><Textarea value={draft.references} onChange={e=>update("references",e.target.value)} placeholder="Paste links or describe designs you want us to take inspiration from." rows={4}/></div></Question>}
 {step===6&&<Question title="How should the slide structure change?" description="Choose how much freedom we have to improve the structure."><div className="space-y-2">{output.map(x=><Choice key={x} selected={draft.output.includes(x)} onClick={()=>toggle("output",x)} label={x}/>)}</div></Question>}
 {step===7&&<Question title="Upload the existing deck" description="The existing presentation is the most important file for this service. You can also add logos, images, brand files, or other references."><label className="border border-dashed border-border rounded-xl p-6 flex flex-col items-center justify-center text-center cursor-pointer hover:border-primary/50"><Upload size={22} className="text-primary mb-2"/><span className="font-medium text-sm">Choose presentation and supporting files</span><span className="text-xs text-muted-foreground mt-1">PPT, PPTX, PDF, images, logos, brand files, or references</span><input type="file" multiple className="hidden" onChange={handleFiles}/></label>{draft.files.length>0&&<div className="mt-4 space-y-2">{draft.files.map(n=><div key={n} className="flex items-center gap-2 text-sm bg-muted/40 rounded-lg px-3 py-2"><FileText size={15} className="text-primary"/><span className="truncate">{n}</span></div>)}</div>}<div className="mt-5"><label className="text-sm font-medium mb-1.5 block">Additional notes <span className="text-muted-foreground font-normal">(optional)</span></label><Textarea value={draft.notes} onChange={e=>update("notes",e.target.value)} placeholder="Anything else we should know about the redesign?" rows={5}/></div></Question>}
 {step===8&&!submitted&&<Question title="Review your redesign request" description="Check the details and confirm your request."><div className="space-y-4"><Review label="Service" value="Existing Deck Redesign — $39"/><Review label="Existing deck" value={draft.project}/><Review label="Redesign goals" value={draft.reasons.join(", ")}/><Review label="Audience" value={draft.audience.join(", ")}/><Review label="Content to preserve" value={draft.keep.join(", ")}/><Review label="Visual style" value={draft.style}/><Review label="Slide structure" value={draft.output.join(", ")}/>{draft.brand&&<Review label="Brand information" value={draft.brand}/>} {draft.references&&<Review label="Design references" value={draft.references}/>} {draft.files.length>0&&<Review label="Files" value={draft.files.join(", ")}/>} {draft.notes&&<Review label="Additional notes" value={draft.notes}/>}</div></Question>}
 {step===8&&submitted&&<section className="text-center py-12"><div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mx-auto mb-6"><Check size={30} className="text-primary"/></div><p className="text-xs font-semibold uppercase tracking-wider text-primary mb-2">Request Submitted</p><h1 className="text-3xl font-bold mb-3">Redesign request received</h1><p className="text-muted-foreground max-w-lg mx-auto mb-7">We'll review your existing deck and requirements. If anything else is needed, we'll use your project conversation to follow up.</p><div className="inline-flex flex-col items-center rounded-xl border border-border bg-card px-8 py-5 mb-7"><span className="text-xs text-muted-foreground uppercase tracking-wider">Project ID</span><span className="text-xl font-bold tracking-wide mt-1">{submitted}</span><Badge className="mt-3 bg-primary/10 text-primary border-primary/20">Pending Review</Badge></div><Button onClick={()=>setLocation("/tasks")} className="bg-primary text-primary-foreground hover:bg-primary/90">View My Tasks</Button></section>}
 {step<8&&<div className="flex gap-3 mt-6">{step>1?<Button variant="outline" onClick={()=>setStep(s=>s-1)} className="flex-1 gap-2"><ChevronLeft size={14}/> Back</Button>:<Button variant="outline" onClick={()=>setLocation("/new-request/presentation")} className="flex-1">Back to Presentation Services</Button>}<Button onClick={()=>valid()&&setStep(s=>s+1)} disabled={!valid()} className="flex-1 bg-primary text-primary-foreground hover:bg-primary/90 gap-2">Continue <ChevronRight size={14}/></Button></div>}
 {step===8&&!submitted&&<div className="flex gap-3 mt-6"><Button variant="outline" onClick={()=>setStep(7)} className="flex-1">Back</Button><Button onClick={submit} disabled={createMutation.isPending} className="flex-1 bg-primary text-primary-foreground hover:bg-primary/90">{createMutation.isPending?"Submitting...":"Confirm & Submit"}</Button></div>}{createMutation.isError&&<p className="text-sm text-destructive text-center mt-4">We couldn't submit the request. Please try again.</p>}</div></ClientLayout>;
}
function Question({title,description,children}:{title:string;description:string;children:React.ReactNode}){return <section className="bg-card border border-border rounded-xl p-5 md:p-6"><h2 className="text-2xl font-bold mb-2">{title}</h2><p className="text-sm text-muted-foreground mb-6">{description}</p>{children}</section>}
function Choice({selected,onClick,label}:{selected:boolean;onClick:()=>void;label:string}){return <button type="button" onClick={onClick} className={`w-full flex items-center text-left rounded-xl border px-4 py-3.5 transition-all ${selected?"border-primary bg-primary/10":"border-border hover:border-primary/40"}`}><span className={`w-5 h-5 rounded-full border flex items-center justify-center mr-3 shrink-0 ${selected?"border-primary bg-primary text-primary-foreground":"border-muted-foreground/40"}`}>{selected&&<Check size={12}/>}</span><span className={selected?"font-medium text-primary":"text-sm"}>{label}</span></button>}
function Review({label,value}:{label:string;value:string}){return <div className="border-b border-border pb-3 last:border-0 last:pb-0"><p className="text-xs text-muted-foreground mb-1">{label}</p><p className="text-sm leading-6 whitespace-pre-wrap">{value}</p></div>}
