import { useState, useRef, useEffect } from "react";
import { ClientLayout } from "@/components/ClientLayout";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Textarea } from "@/components/ui/textarea";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { useListProjects, useListMessages, useSendMessage, useMarkMessagesRead, useGetMe } from "@workspace/api-client-react";
import { getListProjectsQueryKey, getListMessagesQueryKey } from "@workspace/api-client-react";
import { useQueryClient } from "@tanstack/react-query";
import { Send, MessageSquare, Paperclip, X, FileText, Download, ArrowLeft, FileSignature } from "lucide-react";
import { formatDistanceToNow } from "date-fns";
import { OfferCard, type Offer } from "@/components/OfferCard";

function fileToBase64(file: File): Promise<string> { return new Promise((resolve, reject) => { const reader = new FileReader(); reader.readAsDataURL(file); reader.onload = () => { const result = reader.result as string; resolve(result.split(",")[1]); }; reader.onerror = reject; }); }
const ALLOWED_MIME = ["image/png","image/jpeg","image/jpg","image/gif","image/webp","application/pdf","application/msword","application/vnd.openxmlformats-officedocument.wordprocessingml.document","application/zip","application/x-zip-compressed"];
function FilePreview({ url, name, mimeType }: { url: string; name: string; mimeType?: string | null }) { if (mimeType?.startsWith("image/")) return <a href={url} target="_blank" rel="noopener noreferrer" className="block mt-2"><img src={url} alt={name} className="max-w-48 max-h-48 rounded-lg object-cover border border-border" /></a>; return <a href={url} target="_blank" rel="noopener noreferrer" className="flex items-center gap-2 mt-2 bg-background border border-border rounded-lg px-3 py-2 text-xs hover:border-primary/30 transition-all max-w-48"><FileText size={14} className="text-muted-foreground shrink-0" /><span className="truncate">{name}</span><Download size={12} className="text-muted-foreground shrink-0 ml-auto" /></a>; }

export default function Messages() {
  const [selectedProjectId, setSelectedProjectId] = useState<number | null>(null); const [message, setMessage] = useState(""); const [attachedFile, setAttachedFile] = useState<File | null>(null); const [offerDialog, setOfferDialog] = useState(false); const [offerServiceType, setOfferServiceType] = useState(""); const [offerServiceName, setOfferServiceName] = useState(""); const [offerScope, setOfferScope] = useState(""); const [offerRequirements, setOfferRequirements] = useState(""); const [offerPrice, setOfferPrice] = useState(""); const [offerDelivery, setOfferDelivery] = useState(""); const [offerTerms, setOfferTerms] = useState(""); const [offerSaving, setOfferSaving] = useState(false); const [offers, setOffers] = useState<Offer[]>([]);
  const fileInputRef = useRef<HTMLInputElement>(null); const messagesEndRef = useRef<HTMLDivElement>(null); const queryClient = useQueryClient(); const { data: me } = useGetMe(); const { data: projects } = useListProjects({ query: { queryKey: getListProjectsQueryKey() } }); const projectsWithConversation = projects?.filter(p => p.hasConversation) ?? []; const { data: messages, isLoading: messagesLoading } = useListMessages(selectedProjectId ?? 0, { query: { enabled: !!selectedProjectId, queryKey: getListMessagesQueryKey(selectedProjectId ?? 0) } }); const sendMutation = useSendMessage(); const markReadMutation = useMarkMessagesRead();
  const loadOffers = async (projectId: number) => { try { const response = await fetch(`/api/projects/${projectId}/offers`); if (!response.ok) return; const data = await response.json(); setOffers(data.filter((o: Offer) => o.status !== "draft")); } catch {} };
  useEffect(() => { if (selectedProjectId) loadOffers(selectedProjectId); else setOffers([]); }, [selectedProjectId]);
  useEffect(() => { if (selectedProjectId && messages?.length) markReadMutation.mutate({ projectId: selectedProjectId }); }, [selectedProjectId, messages?.length]); useEffect(() => { messagesEndRef.current?.scrollIntoView({ behavior: "smooth" }); }, [messages, offers]);
  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => { const file = e.target.files?.[0]; if (!file) return; if (!ALLOWED_MIME.includes(file.type)) { alert("Unsupported file type. Allowed: images, PDF, DOCX, ZIP"); return; } if (file.size > 10 * 1024 * 1024) { alert("File too large. Maximum 10MB"); return; } setAttachedFile(file); };
  const handleSend = async () => { if ((!message.trim() && !attachedFile) || !selectedProjectId) return; let fileData: string | undefined; let fileName: string | undefined; let fileMimeType: string | undefined; if (attachedFile) { fileData = await fileToBase64(attachedFile); fileName = attachedFile.name; fileMimeType = attachedFile.type; } sendMutation.mutate({ projectId: selectedProjectId, data: { content: message.trim(), fileData, fileName, fileMimeType } }, { onSuccess: () => { queryClient.invalidateQueries({ queryKey: getListMessagesQueryKey(selectedProjectId) }); setMessage(""); setAttachedFile(null); if (fileInputRef.current) fileInputRef.current.value = ""; } }); };
  const selectedProject = projects?.find(p => p.id === selectedProjectId); const isOwner = me?.role === "owner" || me?.role === "admin";
  const openOffer = () => { if (!selectedProject) return; setOfferServiceType(selectedProject.serviceType ?? ""); setOfferServiceName(selectedProject.title ?? ""); setOfferScope(selectedProject.description ?? ""); const req = selectedProject.requirements; setOfferRequirements(req && typeof req === "object" ? Object.entries(req).filter(([k]) => k !== "attached_files").map(([k,v]) => `${k}: ${typeof v === "object" ? JSON.stringify(v) : String(v)}`).join("\n") : req ? String(req) : ""); setOfferPrice(selectedProject.price != null ? String(selectedProject.price) : ""); setOfferDelivery(""); setOfferTerms(""); setOfferDialog(true); };
  const sendOffer = async () => {
    if (!selectedProjectId || !offerServiceType.trim() || !offerServiceName.trim() || !offerScope.trim() || !offerPrice.trim()) { alert("Service, project, scope and price are required."); return; }
    setOfferSaving(true);
    try {
      const response = await fetch(`/api/projects/${selectedProjectId}/offers`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ serviceType: offerServiceType.trim(), serviceName: offerServiceName.trim(), scope: offerScope.trim(), requirements: offerRequirements.trim() || undefined, price: offerPrice.trim(), deliveryEstimate: offerDelivery.trim() || undefined, terms: offerTerms.trim() || undefined, send: true }) });
      const data = await response.json();
      if (!response.ok) throw new Error(data.error || "Unable to send offer");
      setOfferDialog(false);
      await loadOffers(selectedProjectId);
      queryClient.invalidateQueries({ queryKey: getListMessagesQueryKey(selectedProjectId) });
    } catch (error) { alert(error instanceof Error ? error.message : "Unable to send offer"); } finally { setOfferSaving(false); }
  };
  const roleColor = (role: string) => role === "owner" || role === "admin" ? "text-primary" : role === "freelancer" ? "text-blue-400" : "text-muted-foreground"; const roleBadgeText = (role: string) => role === "owner" ? "Owner" : role === "admin" ? "Admin" : role === "freelancer" ? "Freelancer" : null;
  const handleOfferChanged = async (updated: Offer, nextStep?: string) => { setOffers(current => current.map(o => o.id === updated.id ? updated : o)); if (selectedProjectId) { await loadOffers(selectedProjectId); queryClient.invalidateQueries({ queryKey: getListMessagesQueryKey(selectedProjectId) }); } if (nextStep === "payment") alert("Offer accepted. Payment is the next step."); };

  return <ClientLayout><div className="h-full flex overflow-hidden" style={{height:"calc(100vh - 0px)"}}><div className={`${selectedProjectId?"hidden md:flex":"flex"} w-full md:w-72 border-r border-border flex-col shrink-0`}><div className="px-4 py-4 border-b border-border"><h1 className="font-semibold text-sm" data-testid="text-messages-heading">Messages</h1></div><ScrollArea className="flex-1">{projectsWithConversation.length===0?<div className="p-4 text-center text-muted-foreground text-xs mt-4">No conversations yet. Admin will start one after reviewing your request.</div>:<div className="p-2 space-y-1">{projectsWithConversation.map(p=><button key={p.id} onClick={()=>setSelectedProjectId(p.id)} data-testid={`button-project-conversation-${p.id}`} className={`w-full text-left px-3 py-3 rounded-lg transition-colors ${selectedProjectId===p.id?"bg-primary/10 border border-primary/20":"hover:bg-accent"}`}><p className="text-sm font-medium truncate">{p.title}</p><p className="text-xs text-muted-foreground mt-0.5">{p.serviceType}</p></button>)}</div>}</ScrollArea></div>
  <div className={`${selectedProjectId?"flex":"hidden md:flex"} flex-1 min-w-0 flex-col`}>{!selectedProjectId?<div className="flex-1 flex flex-col items-center justify-center text-muted-foreground"><MessageSquare size={40} className="mb-3 opacity-30"/><p className="text-sm">Select a conversation</p></div>:<><div className="px-4 md:px-5 py-3 md:py-4 border-b border-border flex items-center gap-2 shrink-0"><Button variant="ghost" size="sm" className="md:hidden h-8 w-8 p-0" onClick={()=>setSelectedProjectId(null)} aria-label="Back to conversations"><ArrowLeft size={16}/></Button><div className="min-w-0"><p className="font-semibold text-sm truncate">{selectedProject?.title}</p><p className="text-xs text-muted-foreground truncate">{selectedProject?.serviceType}</p></div></div>
  <ScrollArea className="flex-1 p-3 md:p-4">{messagesLoading?<div className="space-y-3">{[1,2,3].map(i=><div key={i} className="h-10 bg-muted animate-pulse rounded-lg"/>)}</div>:!messages?.length&&!offers.length?<div className="text-center text-muted-foreground text-sm py-8">No messages yet. Say hello!</div>:<div className="space-y-4">{messages?.map(msg=>{const isMe=msg.senderId===me?.id;const badge=roleBadgeText(msg.senderRole);return <div key={msg.id} className={`flex ${isMe?"justify-end":"justify-start"}`} data-testid={`message-${msg.id}`}><div className={`max-w-[85%] md:max-w-[75%] ${isMe?"items-end":"items-start"} flex flex-col gap-1`}>{!isMe&&<div className="flex items-center gap-1.5 mb-0.5"><span className={`text-xs font-medium ${roleColor(msg.senderRole)}`}>{msg.senderName}</span>{badge&&<Badge className={`text-[9px] border-0 h-4 ${msg.senderRole==="client"?"bg-muted/10 text-muted-foreground":"bg-primary/10 text-primary"}`}>{badge}</Badge>}</div>}<div className={`px-4 py-2.5 rounded-2xl text-sm ${isMe?"bg-primary text-primary-foreground":"bg-card border border-border"}`}>{msg.content&&<p>{msg.content}</p>}{msg.fileUrl&&msg.fileName&&<FilePreview url={msg.fileUrl} name={msg.fileName} mimeType={msg.fileMimeType}/>}</div><span className="text-[10px] text-muted-foreground">{formatDistanceToNow(new Date(msg.createdAt),{addSuffix:true})}{isMe&&<span className="ml-1">{msg.isRead?"· Read":"· Sent"}</span>}</span></div></div>})}{offers.map(offer=><div key={`offer-${offer.id}`} className="flex justify-start"><OfferCard offer={offer} canRespond={!isOwner} isOwner={isOwner} onChanged={handleOfferChanged}/></div>)}<div ref={messagesEndRef}/></div>}</ScrollArea>
  {attachedFile&&<div className="px-4 pb-2"><div className="flex items-center gap-2 bg-card border border-border rounded-lg px-3 py-2 text-xs"><FileText size={14} className="text-muted-foreground"/><span className="truncate flex-1">{attachedFile.name}</span><span className="text-muted-foreground shrink-0">{(attachedFile.size/1024).toFixed(0)}KB</span><button onClick={()=>{setAttachedFile(null);if(fileInputRef.current)fileInputRef.current.value="";}}><X size={14}/></button></div></div>}
  <div className="p-3 md:p-4 border-t border-border shrink-0"><div className="flex gap-2"><input ref={fileInputRef} type="file" className="hidden" accept=".png,.jpg,.jpeg,.gif,.webp,.pdf,.doc,.docx,.zip" onChange={handleFileChange}/><Button variant="outline" size="sm" className="h-9 w-9 p-0 shrink-0" onClick={()=>fileInputRef.current?.click()} title="Attach file"><Paperclip size={14}/></Button>{isOwner&&<Button variant="outline" size="sm" className="h-9 px-2 shrink-0 gap-1" onClick={openOffer} title="Create Offer"><FileSignature size={14}/><span className="hidden sm:inline">Offer</span></Button>}<Input value={message} onChange={e=>setMessage(e.target.value)} placeholder="Type a message..." onKeyDown={e=>e.key==="Enter"&&!e.shiftKey&&handleSend()} className="flex-1 text-sm min-w-0" data-testid="input-message"/><Button onClick={handleSend} disabled={(!message.trim()&&!attachedFile)||sendMutation.isPending} className="bg-primary text-primary-foreground hover:bg-primary/90" data-testid="button-send-message"><Send size={14}/></Button></div></div>
  </>}</div></div>
  <Dialog open={offerDialog} onOpenChange={setOfferDialog}><DialogContent className="sm:max-w-2xl max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>Create Project Offer</DialogTitle></DialogHeader>{selectedProject&&<div className="space-y-4"><div className="rounded-lg border border-border bg-muted/20 p-3 text-sm"><p className="font-medium">{selectedProject.title}</p><p className="text-xs text-muted-foreground">{selectedProject.projectCode??`Project #${selectedProject.id}`} · {selectedProject.clientName??"Client"}</p><p className="text-xs text-muted-foreground mt-1">Original request: {selectedProject.serviceType}</p></div><div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><div><label className="text-xs font-medium mb-1.5 block">Service</label><Input value={offerServiceType} onChange={e=>setOfferServiceType(e.target.value)}/></div><div><label className="text-xs font-medium mb-1.5 block">Project / Service Name</label><Input value={offerServiceName} onChange={e=>setOfferServiceName(e.target.value)}/></div></div><div><label className="text-xs font-medium mb-1.5 block">Scope of Work</label><Textarea value={offerScope} onChange={e=>setOfferScope(e.target.value)} rows={5}/></div><div><label className="text-xs font-medium mb-1.5 block">Requirements</label><Textarea value={offerRequirements} onChange={e=>setOfferRequirements(e.target.value)} rows={4}/></div><div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><div><label className="text-xs font-medium mb-1.5 block">Price (USD)</label><Input type="number" min="0" step="0.01" value={offerPrice} onChange={e=>setOfferPrice(e.target.value)}/></div><div><label className="text-xs font-medium mb-1.5 block">Delivery Estimate</label><Input value={offerDelivery} onChange={e=>setOfferDelivery(e.target.value)} placeholder="e.g. 5 business days"/></div></div><div><label className="text-xs font-medium mb-1.5 block">Terms / Notes</label><Textarea value={offerTerms} onChange={e=>setOfferTerms(e.target.value)} rows={3}/></div><div className="flex gap-2 pt-2"><Button variant="outline" onClick={()=>setOfferDialog(false)} className="flex-1">Cancel</Button><Button onClick={sendOffer} disabled={offerSaving} className="flex-1 gap-2 bg-primary text-primary-foreground hover:bg-primary/90"><FileSignature size={15}/>{offerSaving?"Sending...":"Send Offer"}</Button></div></div>}</DialogContent></Dialog>
  </ClientLayout>;
}
