import { useState } from "react";
import { useLocation } from "wouter";
import { ClientLayout } from "@/components/ClientLayout";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Check, ChevronLeft, ChevronRight, FileText, Upload } from "lucide-react";
import { useCreateProject, getListProjectsQueryKey } from "@workspace/api-client-react";
import { useQueryClient } from "@tanstack/react-query";

const services=[
  {name:"Pitch Deck (Up to 10 Slides)",price:59},
  {name:"Company Profile",price:49},
  {name:"Existing Deck Redesign",price:39},
];
const purposes=["Investor pitch / fundraising","Sales presentation","Product or service presentation","Partnership proposal","Company introduction","Other"];
const audiences=["Investors","Potential customers","Business partners","Management / team","General audience","Other"];
const contentOptions=["Company overview","Problem / opportunity","Solution / product","Market opportunity","Business model","Competition","Traction / achievements","Team","Financial information","Contact / call to action"];
const styles=["Clean & corporate","Modern & minimal","Bold & creative","Premium / executive","Technology / startup","I have a reference style"];

type Draft={service:string;project:string;purpose:string[];audience:string[];content:string[];style:string;brand:string;references:string;files:string[];notes:string};
const empty:Draft={service:"",project:"",purpose:[],audience:[],content:[],style:"",brand:"",references:"",files:[],notes:""};

export default function PresentationDesignRequest(){
 const[,setLocation]=useLocation(); const queryClient=useQueryClient(); const createMutation=useCreateProject(); const[step,setStep]=useState(1); const[draft,setDraft]=useState<Draft>(empty); const[submitted,setSubmitted]=useState<string|null>(null);
 const selected=services.find(s=>s.name===draft.service)??null;
 const update=<K extends keyof Draft>(key:K,value:Draft[K])=>setDraft(d=>({...d,[key]:value}));
 const toggle=(key:"purpose"|"audience"|"content",value:string)=>setDraft(d=>({...d,[key]:d[key].includes(value)?d[key].filter(x=>x!==value):[...d[key],value]}));
 const valid=()=>{if(step===1)return !!draft.service;if(step===2)return draft.project.trim().length>=5;if(step===3)return draft.purpose.length>0;if(step===4)return draft.audience.length>0;if(step===5)return draft.content.length>0;if(step===6)return !!draft.style;return true};
 const handleFiles=(e:React.ChangeEvent<HTMLInputElement>)=>{const names=Array.from(e.target.files??[]).map(f=>f.name);update("files",[...new Set([...draft.files,...names])]);e.target.value=""};
 const submit=()=>{if(!selected)return; const requirements={service:selected.name,project_description:draft.project.trim(),presentation_purpose:draft.purpose,target_audience:draft.audience,requested_content:draft.content,visual_style:draft.style,brand_information:draft.brand.trim(),design_references:draft.references.trim(),attached_files:draft.files,additional_notes:draft.notes.trim()}; createMutation.mutate({data:{serviceType:selected.name,title:`${selected.name} Request`,description:draft.project.trim(),priority:"medium",price:selected.price,requirements} as any},{onSuccess:p=>{queryClient.invalidateQueries({queryKey:getListProjectsQueryKey()});setSubmitted(p.projectCode??`GBX-${p.id}`);}})};
 const labels=["Service","Project","Purpose","Audience","Content","Style","Files","Review"];
 return <ClientLayout><div className="p-4 md:p-6 max-w-3xl mx-auto w-full">
  <div className="mb-7"><div className="flex items-center justify-between mb-3"><div><p className="text-xs font-semibold uppercase tracking-wider text-primary">Presentation Design</p><h1 className="text-2xl font-bold mt-1">Let's plan your presentation</h1></div><span className="text-sm text-muted-foreground">Step {step} of 8</span></div><div className="flex gap-1.5">{labels.map((x,i)=><div key={x} className="flex-1"><div className={`h-1.5 rounded-full ${i+1<=step?"bg-primary":"bg-muted"}`}/><p className="text-[10px] text-muted-foreground mt-1 hidden sm:block">{x}</p></div>)}</div></div>
  {step===1&&<Question title="Choose your presentation service" description="Select the type of presentation work you need."><div className="space-y-2">{services.map(s=><Choice key={s.name} selected={draft.service===s.name} onClick={()=>update("service",s.name)} label={s.name} price={s.price}/>)}</div></Question>}
  {step===2&&<Question title="Tell us about the project" description="What company, product, service, or idea is this presentation about?"><Textarea value={draft.project} onChange={e=>update("project",e.target.value)} placeholder="Example: We are a SaaS startup helping small businesses automate customer bookings." rows={7} autoFocus/></Question>}
  {step===3&&<Question title="What is the purpose?" description="Select everything that applies."><div className="grid gap-2 sm:grid-cols-2">{purposes.map(x=><Choice key={x} selected={draft.purpose.includes(x)} onClick={()=>toggle("purpose",x)} label={x}/>)}</div></Question>}
  {step===4&&<Question title="Who will see it?" description="Select the audience you want the presentation to speak to."><div className="grid gap-2 sm:grid-cols-2">{audiences.map(x=><Choice key={x} selected={draft.audience.includes(x)} onClick={()=>toggle("audience",x)} label={x}/>)}</div></Question>}
  {step===5&&<Question title="What content should be included?" description="Choose the sections you already have or want us to include. We can help refine the structure during review."><div className="grid gap-2 sm:grid-cols-2">{contentOptions.map(x=><Choice key={x} selected={draft.content.includes(x)} onClick={()=>toggle("content",x)} label={x}/>)}</div></Question>}
  {step===6&&<Question title="Choose the visual direction" description="Select the style that best matches what you want."><div className="space-y-2">{styles.map(x=><Choice key={x} selected={draft.style===x} onClick={()=>update("style",x)} label={x}/>)}</div><div className="mt-5"><label className="text-sm font-medium mb-1.5 block">Brand information <span className="text-muted-foreground font-normal">(optional)</span></label><Textarea value={draft.brand} onChange={e=>update("brand",e.target.value)} placeholder="Brand colors, fonts, logo guidelines, or anything we should follow." rows={4}/></div><div className="mt-4"><label className="text-sm font-medium mb-1.5 block">Design references <span className="text-muted-foreground font-normal">(optional)</span></label><Textarea value={draft.references} onChange={e=>update("references",e.target.value)} placeholder="Paste links or describe presentations you like." rows={4}/></div></Question>}
  {step===7&&<Question title="Add your files and notes" description="Upload anything that will help us create the presentation. This can include your logo, existing copy, data, images, or previous slides."><label className="border border-dashed border-border rounded-xl p-6 flex flex-col items-center justify-center text-center cursor-pointer hover:border-primary/50"><Upload size={22} className="text-primary mb-2"/><span className="font-medium text-sm">Choose helpful files</span><span className="text-xs text-muted-foreground mt-1">Logo, text, images, spreadsheets, or previous presentations</span><input type="file" multiple className="hidden" onChange={handleFiles}/></label>{draft.files.length>0&&<div className="mt-4 space-y-2">{draft.files.map(n=><div key={n} className="flex items-center gap-2 text-sm bg-muted/40 rounded-lg px-3 py-2"><FileText size={15} className="text-primary"/><span className="truncate">{n}</span></div>)}</div>}<div className="mt-5"><label className="text-sm font-medium mb-1.5 block">Additional notes <span className="text-muted-foreground font-normal">(optional)</span></label><Textarea value={draft.notes} onChange={e=>update("notes",e.target.value)} placeholder="Anything else we should know?" rows={5}/></div></Question>}
  {step===8&&!submitted&&<Question title="Review your request" description="Check the details below before submitting."><div className="space-y-4"><Review label="Service" value={`${selected?.name??""} — $${selected?.price??""}`}/><Review label="Project" value={draft.project}/><Review label="Purpose" value={draft.purpose.join(", ")}/><Review label="Audience" value={draft.audience.join(", ")}/><Review label="Content" value={draft.content.join(", ")}/><Review label="Visual style" value={draft.style}/>{draft.brand&&<Review label="Brand information" value={draft.brand}/>} {draft.references&&<Review label="Design references" value={draft.references}/>} {draft.files.length>0&&<Review label="Files" value={draft.files.join(", ")}/>} {draft.notes&&<Review label="Additional notes" value={draft.notes}/>}</div></Question>}
  {step===8&&submitted&&<section className="text-center py-12"><div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mx-auto mb-6"><Check size={30} className="text-primary"/></div><p className="text-xs font-semibold uppercase tracking-wider text-primary mb-2">Request Submitted</p><h1 className="text-3xl font-bold mb-3">We have received your request.</h1><p className="text-muted-foreground max-w-lg mx-auto mb-7">We'll review your presentation requirements and contact you through your project conversation if we need anything else.</p><div className="inline-flex flex-col items-center rounded-xl border border-border bg-card px-8 py-5 mb-7"><span className="text-xs text-muted-foreground uppercase tracking-wider">Project ID</span><span className="text-xl font-bold tracking-wide mt-1">{submitted}</span><Badge className="mt-3 bg-primary/10 text-primary border-primary/20">Pending Review</Badge></div><Button onClick={()=>setLocation("/tasks")} className="bg-primary text-primary-foreground hover:bg-primary/90">View My Tasks</Button></section>}
  {step<8&&<div className="flex gap-3 mt-6">{step>1?<Button variant="outline" onClick={()=>setStep(s=>s-1)} className="flex-1 gap-2"><ChevronLeft size={14}/> Back</Button>:<Button variant="outline" onClick={()=>setLocation("/new-request")} className="flex-1">Back to Services</Button>}<Button onClick={()=>valid()&&setStep(s=>s+1)} disabled={!valid()} className="flex-1 bg-primary text-primary-foreground hover:bg-primary/90 gap-2">Continue <ChevronRight size={14}/></Button></div>}
  {step===8&&!submitted&&<div className="flex gap-3 mt-6"><Button variant="outline" onClick={()=>setStep(7)} className="flex-1">Back</Button><Button onClick={submit} disabled={createMutation.isPending} className="flex-1 bg-primary text-primary-foreground hover:bg-primary/90">{createMutation.isPending?"Submitting...":"Confirm & Submit"}</Button></div>}{createMutation.isError&&<p className="text-sm text-destructive text-center mt-4">We couldn't submit the request. Please try again.</p>}
 </div></ClientLayout>;
}
function Question({title,description,children}:{title:string;description:string;children:React.ReactNode}){return <section className="bg-card border border-border rounded-xl p-5 md:p-6"><h2 className="text-2xl font-bold mb-2">{title}</h2><p className="text-sm text-muted-foreground mb-6">{description}</p>{children}</section>}
function Choice({selected,onClick,label,price}:{selected:boolean;onClick:()=>void;label:string;price?:number}){return <button type="button" onClick={onClick} className={`w-full flex items-center justify-between text-left rounded-xl border px-4 py-3.5 transition-all ${selected?"border-primary bg-primary/10":"border-border hover:border-primary/40"}`}><span className="flex items-center gap-3"><span className={`w-5 h-5 rounded-full border flex items-center justify-center shrink-0 ${selected?"border-primary bg-primary text-primary-foreground":"border-muted-foreground/40"}`}>{selected&&<Check size={12}/>}</span><span className={selected?"font-medium text-primary":"text-sm"}>{label}</span></span>{price!==undefined&&<span className="font-bold text-primary">${price}</span>}</button>}
function Review({label,value}:{label:string;value:string}){return <div className="border-b border-border pb-3 last:border-0 last:pb-0"><p className="text-xs text-muted-foreground mb-1">{label}</p><p className="text-sm leading-6 whitespace-pre-wrap">{value}</p></div>}
