import { useEffect, useState } from "react";
import { useLocation } from "wouter";
import { ClientLayout } from "@/components/ClientLayout";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Check, ChevronLeft, ChevronRight } from "lucide-react";
import { useCreateProject, getListProjectsQueryKey } from "@workspace/api-client-react";
import { useQueryClient } from "@tanstack/react-query";

const STORAGE_KEY = "gbolix-supabase-request-draft";
const dbOptions = ["I need a new database structure", "I already have tables", "I need help designing the database", "I'm migrating an existing database"];
const dataOptions = ["User profiles", "Products / services", "Orders / transactions", "Bookings / appointments", "Messages / conversations", "Files / documents", "Custom tables"];
const authOptions = ["Connect existing authentication", "Set up Supabase Auth", "Email + password", "Google / social login", "Phone / OTP", "I need advice"];
const storageOptions = ["No file storage needed", "Profile photos", "Product / media files", "Documents", "User uploads", "Other files"];
const apiOptions = ["Read data", "Create records", "Update records", "Delete records", "Search / filtering", "Realtime updates", "Edge Functions", "Other API logic"];

type Draft = {
 projectName:string; platform:string; projectLink:string; description:string; supabaseStatus:string; supabaseUrl:string; dbPlan:string[]; dataTypes:string[]; auth:string[]; storage:string[]; api:string[]; security:string; notes:string;
};
const emptyDraft:Draft={projectName:"",platform:"",projectLink:"",description:"",supabaseStatus:"",supabaseUrl:"",dbPlan:[],dataTypes:[],auth:[],storage:[],api:[],security:"",notes:""};

export default function SupabaseRequest(){
 const [,setLocation]=useLocation(); const queryClient=useQueryClient(); const createMutation=useCreateProject();
 const [step,setStep]=useState(1); const [draft,setDraft]=useState<Draft>(emptyDraft); const [submittedCode,setSubmittedCode]=useState<string|null>(null);
 useEffect(()=>{try{const saved=localStorage.getItem(STORAGE_KEY);if(saved)setDraft({...emptyDraft,...JSON.parse(saved)});}catch{}},[]);
 useEffect(()=>{if(Object.values(draft).some(v=>Array.isArray(v)?v.length>0:Boolean(v)))localStorage.setItem(STORAGE_KEY,JSON.stringify(draft));},[draft]);
 const update=<K extends keyof Draft>(key:K,value:Draft[K])=>setDraft(c=>({...c,[key]:value}));
 const toggle=(key:"dbPlan"|"dataTypes"|"auth"|"storage"|"api",value:string)=>setDraft(c=>({...c,[key]:c[key].includes(value)?c[key].filter(x=>x!==value):[...c[key],value]}));
 const canContinue=()=>{if(step===1)return draft.projectName.trim().length>=2&&Boolean(draft.platform)&&draft.description.trim().length>=10;if(step===2)return Boolean(draft.supabaseStatus);if(step===3)return draft.dbPlan.length>0;if(step===4)return draft.dataTypes.length>0;if(step===5)return draft.auth.length>0;if(step===6)return draft.storage.length>0;if(step===7)return draft.api.length>0;if(step===8)return Boolean(draft.security);return true;};
 const submit=()=>{const requirements={project_name:draft.projectName.trim(),platform:draft.platform,project_link:draft.projectLink.trim(),project_description:draft.description.trim(),supabase_status:draft.supabaseStatus,supabase_project_url:draft.supabaseUrl.trim(),database_plan:draft.dbPlan,data_requirements:draft.dataTypes,authentication_requirements:draft.auth,storage_requirements:draft.storage,api_backend_requirements:draft.api,security_requirements:draft.security,additional_notes:draft.notes.trim()};createMutation.mutate({data:{serviceType:"Supabase Integration",title:"Supabase Integration Request",description:draft.description.trim(),priority:"medium",price:119,requirements} as any},{onSuccess:p=>{queryClient.invalidateQueries({queryKey:getListProjectsQueryKey()});setSubmittedCode(p.projectCode??`GBX-${p.id}`);localStorage.removeItem(STORAGE_KEY);setStep(10);}})};
 const labels=["Project","Supabase","Database","Data","Auth","Storage","API","Security","Review"];
 return <ClientLayout><div className="p-4 md:p-6 max-w-3xl mx-auto w-full">
 {step<10&&<div className="mb-7"><div className="flex items-center justify-between mb-3"><div><p className="text-xs font-semibold uppercase tracking-wider text-primary">FlutterFlow / Bubble MVP</p><h1 className="text-2xl font-bold mt-1">Supabase Integration</h1></div><span className="text-sm text-muted-foreground">Step {step} of 9</span></div><div className="flex gap-1.5">{labels.map((x,i)=><div key={x} className="flex-1"><div className={`h-1.5 rounded-full ${i+1<=step?"bg-primary":"bg-muted"}`}/><p className="text-[10px] text-muted-foreground mt-1 hidden sm:block">{x}</p></div>)}</div></div>}
 {step===1&&<Question title="Tell us about your project" description="Give us the project details we need before connecting Supabase."><div className="space-y-5"><Field label="Project name"><input className="w-full rounded-md border border-input bg-background px-3 py-2.5 text-sm" value={draft.projectName} onChange={e=>update("projectName",e.target.value)} placeholder="Example: Gbolix Marketplace" autoFocus/></Field><Field label="Platform"><div className="grid grid-cols-2 gap-2"><Choice selected={draft.platform==="FlutterFlow"} onClick={()=>update("platform","FlutterFlow")} label="FlutterFlow"/><Choice selected={draft.platform==="Bubble"} onClick={()=>update("platform","Bubble")} label="Bubble"/></div></Field><Field label="Project link (optional)"><input className="w-full rounded-md border border-input bg-background px-3 py-2.5 text-sm" value={draft.projectLink} onChange={e=>update("projectLink",e.target.value)} placeholder="Paste your FlutterFlow/Bubble project or preview link"/></Field><Field label="What should the app do?"><Textarea value={draft.description} onChange={e=>update("description",e.target.value)} placeholder="Describe the app and the data it needs to store or retrieve." rows={6}/></Field></div></Question>}
 {step===2&&<Question title="What is your current Supabase setup?" description="Tell us what already exists so we know whether to connect, configure, or build the backend foundation."><div className="space-y-2">{[["existing","I already have a Supabase project"],["new","I need a new Supabase project set up"],["partial","I have Supabase but it is partially configured"],["unsure","I'm not sure what I need yet"]].map(([v,l])=><Choice key={v} selected={draft.supabaseStatus===v} onClick={()=>update("supabaseStatus",v)} label={l}/>)}</div><div className="mt-5"><Field label="Supabase project URL (optional)"><input className="w-full rounded-md border border-input bg-background px-3 py-2.5 text-sm" value={draft.supabaseUrl} onChange={e=>update("supabaseUrl",e.target.value)} placeholder="https://your-project.supabase.co"/></Field></div></Question>}
 {step===3&&<Question title="What database work do you need?" description="Select all that apply. We'll use this to understand the database setup required."><div className="space-y-2">{dbOptions.map(x=><Choice key={x} selected={draft.dbPlan.includes(x)} onClick={()=>toggle("dbPlan",x)} label={x}/>)}</div></Question>}
 {step===4&&<Question title="What data will your app manage?" description="Select the main types of information your database needs to store."><div className="grid gap-2 sm:grid-cols-2">{dataOptions.map(x=><Choice key={x} selected={draft.dataTypes.includes(x)} onClick={()=>toggle("dataTypes",x)} label={x}/>)}</div></Question>}
 {step===5&&<Question title="How should authentication connect to Supabase?" description="Select all authentication requirements that apply to your project."><div className="grid gap-2 sm:grid-cols-2">{authOptions.map(x=><Choice key={x} selected={draft.auth.includes(x)} onClick={()=>toggle("auth",x)} label={x}/>)}</div></Question>}
 {step===6&&<Question title="What will you use Supabase Storage for?" description="Choose the types of files your app needs to store, or select no storage if you don't need it."><div className="grid gap-2 sm:grid-cols-2">{storageOptions.map(x=><Choice key={x} selected={draft.storage.includes(x)} onClick={()=>toggle("storage",x)} label={x}/>)}</div></Question>}
 {step===7&&<Question title="What should the app do with the backend?" description="Select the database operations and backend capabilities you need."><div className="grid gap-2 sm:grid-cols-2">{apiOptions.map(x=><Choice key={x} selected={draft.api.includes(x)} onClick={()=>toggle("api",x)} label={x}/>)}</div></Question>}
 {step===8&&<Question title="Security & additional requirements" description="Tell us about any access-control or security requirements before we review the request."><div className="space-y-2">{[["standard","Standard authenticated access is fine"],["roles","Different users need different access"],["rls","I need Row Level Security configured"],["custom","I have specific security requirements"]].map(([v,l])=><Choice key={v} selected={draft.security===v} onClick={()=>update("security",v)} label={l}/>)}</div><div className="mt-5"><Field label="Additional notes (optional)"><Textarea value={draft.notes} onChange={e=>update("notes",e.target.value)} placeholder="Anything else we should know about the database, integrations, permissions, or backend?" rows={5}/></Field></div></Question>}
 {step===9&&<Question title="Review your request" description="Review everything before submitting your Supabase Integration request."><div className="rounded-xl border border-border bg-muted/20 p-4 space-y-3"><Review label="Service" value="Supabase Integration — $119"/><Review label="Project" value={`${draft.projectName} · ${draft.platform}`}/><Review label="Project link" value={draft.projectLink||"Not provided"}/><Review label="Description" value={draft.description}/><Review label="Supabase setup" value={draft.supabaseStatus}/><Review label="Database work" value={draft.dbPlan.join(", ")}/><Review label="Data" value={draft.dataTypes.join(", ")}/><Review label="Authentication" value={draft.auth.join(", ")}/><Review label="Storage" value={draft.storage.join(", ")}/><Review label="API / backend" value={draft.api.join(", ")}/><Review label="Security" value={draft.security}/><Review label="Additional requirements" value={draft.notes||"None"}/></div></Question>}
 {step===10&&submittedCode&&<section className="text-center py-12"><div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mx-auto mb-6"><Check size={30} className="text-primary"/></div><p className="text-xs font-semibold uppercase tracking-wider text-primary mb-2">Request Submitted</p><h1 className="text-3xl font-bold mb-3">Supabase request received.</h1><p className="text-muted-foreground max-w-lg mx-auto mb-7">We'll review the requirements and continue through your project conversation if anything else is needed.</p><div className="inline-flex flex-col items-center rounded-xl border border-border bg-card px-8 py-5 mb-7"><span className="text-xs text-muted-foreground uppercase tracking-wider">Project ID</span><span className="text-xl font-bold tracking-wide mt-1">{submittedCode}</span><Badge className="mt-3 bg-primary/10 text-primary border-primary/20">Pending Review</Badge></div><Button onClick={()=>setLocation("/tasks")} className="bg-primary text-primary-foreground hover:bg-primary/90">View My Tasks</Button></section>}
 {step<9&&<div className="flex gap-3 mt-6">{step>1?<Button variant="outline" onClick={()=>setStep(s=>Math.max(1,s-1))} className="flex-1 gap-2"><ChevronLeft size={14}/> Back</Button>:<Button variant="outline" onClick={()=>setLocation("/new-request/flutterflow")} className="flex-1">Back to MVP Services</Button>}<Button onClick={()=>canContinue()&&setStep(s=>Math.min(9,s+1))} disabled={!canContinue()} className="flex-1 bg-primary text-primary-foreground hover:bg-primary/90 gap-2">Continue <ChevronRight size={14}/></Button></div>}
 {step===9&&<div className="flex gap-3 mt-6"><Button variant="outline" onClick={()=>setStep(8)} className="flex-1">Back</Button><Button onClick={submit} disabled={createMutation.isPending} className="flex-1 bg-primary text-primary-foreground hover:bg-primary/90">{createMutation.isPending?"Submitting...":"Confirm & Submit"}</Button></div>}
 {createMutation.isError&&<p className="text-sm text-destructive text-center mt-4">We couldn't submit the request. Please try again.</p>}
 </div></ClientLayout>
}
function Question({title,description,children}:{title:string;description:string;children:React.ReactNode}){return <section className="bg-card border border-border rounded-xl p-5 md:p-6"><h2 className="text-2xl font-bold mb-2">{title}</h2><p className="text-sm text-muted-foreground mb-6">{description}</p>{children}</section>}
function Choice({selected,onClick,label}:{selected:boolean;onClick:()=>void;label:string}){return <button type="button" onClick={onClick} className={`w-full flex items-center gap-3 text-left rounded-xl border px-4 py-3.5 transition-all ${selected?"border-primary bg-primary/10":"border-border hover:border-primary/40"}`}><span className={`w-5 h-5 rounded-full border flex items-center justify-center shrink-0 ${selected?"border-primary bg-primary text-primary-foreground":"border-muted-foreground/40"}`}>{selected&&<Check size={12}/>}</span><span className={selected?"font-medium text-primary":"text-sm"}>{label}</span></button>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div><label className="text-sm font-medium mb-1.5 block">{label}</label>{children}</div>}
function Review({label,value}:{label:string;value:string}){return <div><p className="text-xs text-muted-foreground">{label}</p><p className="text-sm mt-0.5 whitespace-pre-wrap">{value}</p></div>}
